// Fichier généré automatiquement le 2026-05-31T08:40:31.978Z
// Ne pas modifier manuellement

export const lastUpdate = "8:40:31 AM 5/31/2026";

export const sources = [
    {
        "handle": "@EtienneTillierStudio",
        "name": "Etienne Tillier",
        "id": "UCUlm3shqkgVNHLomYWZsfYA",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@Simon_bcome",
        "name": "Simon Music",
        "id": "UCaryUIRfj7KAikH_ogrOzig",
        "theme": "Business & Monétisation IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@HenriExplorIA",
        "name": "Henri · ExplorIA",
        "id": "UCxx03UqvjTy9w8iomLwTSuQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@elliottpierret",
        "name": "Elliott Pierret",
        "id": "UCnJAGhDDEPdvY2g4ipf9PMQ",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@RenaudDekode",
        "name": "Renaud Dékode",
        "id": "UCOWu-2h4IpoEjhsRlTuesFg",
        "theme": "Actualités Tech",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@ousmanedf",
        "name": "Ousmane Automatise",
        "id": "UC1o5Eo5Qf12_f6D836PsoPw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@yassine-sdiri",
        "name": "Yassine Sdiri",
        "id": "UC94UeaPuTt_L51RkDxj9d_w",
        "theme": "Business & Monétisation IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@cedric_effi10",
        "name": "Cédric Girard",
        "id": "UCjhLy8XRh4Q0NM2CD6pFPYQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@EliottMeunier",
        "name": "Eliott Meunier",
        "id": "UCPo1nFSGNkyzrA9yvtkEvIw",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@reverdybusiness",
        "name": "Lucas Reverdy",
        "id": "UCabbBG5KYGtdTibrl_XHLOw",
        "theme": "Business & Monétisation IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@JulienSnsn",
        "name": "Julien Sanson",
        "id": "UCK85rF_WKv1N6ojTzVbj3yw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@NerdyKings",
        "name": "Nerdy Kings",
        "id": "UCp7vimq7dYKiVAJLPyI0GcA",
        "theme": "Outils & Modèles IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@iAlan_automatise",
        "name": "iAlan",
        "id": "UCdROsT8FZ2pacpipymmmaPw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@LouisGraffeuil",
        "name": "Louis Graffeuil",
        "id": "UChkCdoCUCNYizE8d9TXsi4A",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@Hugo_Buisson",
        "name": "Hugo Buisson",
        "id": "UCeZvp_y5meYlfcGCFhl6UJQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@audelalia",
        "name": "Au-delà l'IA",
        "id": "UCNSPV84q4QlUtle6MS_7v1Q",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@thomasbssh",
        "name": "Thomas Berton",
        "id": "UCxOWUTmenPJj5V6_g2-CS1g",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@JonasEkanbo",
        "name": "Jonas Ekanbo",
        "id": "UCF2fb5WylqKbw0SgOlJKXMA",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@LudovicSalenne",
        "name": "Ludo Salenne",
        "id": "UCnnYqSNKKygemgmxC9PyLTw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@AurelienAutomatisation",
        "name": "Aurélien Fagioli",
        "id": "UCdL89Z0gQUDc1HT1882AGLw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@BaptIA",
        "name": "Baptiste Simard - IA",
        "id": "UCzabGLybo9x307MkDtqTyFQ",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@LudovicNedelec",
        "name": "Ludovic Nédélec",
        "id": "UCMJ00y5KeFDKzYh9D6Lc41A",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    }
];

export const themes = [
    "Tous",
    "Agents & Automatisation",
    "Vibe Coding & Dev IA",
    "Outils & Modèles IA",
    "Business & Monétisation IA",
    "Productivité & Second Cerveau",
    "Actualités Tech"
];

export const allVideos = [
    {
        "id": "OhT8HBfsRo0",
        "videoId": "OhT8HBfsRo0",
        "title": "Quelqu'un vient de sortir une API gratuite avec 11 modèles d'IA",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=OhT8HBfsRo0",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Quelqu'un vient de sortir une API gratuite avec 11 modèles d'IA..."
    },
    {
        "id": "gLy0lgWFW7Q",
        "videoId": "gLy0lgWFW7Q",
        "title": "ElevenLabs : opéra à metal en IA",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=gLy0lgWFW7Q",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : ElevenLabs : opéra à metal en IA..."
    },
    {
        "id": "kmuTmB-12nc",
        "videoId": "kmuTmB-12nc",
        "title": "Mistral lance son offensive IA",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=kmuTmB-12nc",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Mistral lance son offensive IA..."
    },
    {
        "id": "pjRKfnlsTfk",
        "videoId": "pjRKfnlsTfk",
        "title": "Le vrai problème de l'IA en entreprise (que les consultants cachent)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=pjRKfnlsTfk",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le vrai problème de l'IA en entreprise (que les consultants cachent)..."
    },
    {
        "id": "MXs3pnS9ie4",
        "videoId": "MXs3pnS9ie4",
        "title": "OPUS 4 8 est sorti: qu'est-ce qu'il vaut? 🧠",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=MXs3pnS9ie4",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : OPUS 4 8 est sorti: qu'est-ce qu'il vaut? 🧠..."
    },
    {
        "id": "oNfx1PdTXfU",
        "videoId": "oNfx1PdTXfU",
        "title": "OPUS 4.8 est arrivé: tout connaître en 12 min (sans HYPE)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=oNfx1PdTXfU",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : OPUS 4.8 est arrivé: tout connaître en 12 min (sans HYPE)..."
    },
    {
        "id": "tmXpiLrw3zA",
        "videoId": "tmXpiLrw3zA",
        "title": "J'ai refait Pokémon avec Claude Opus 4.8 en un seul prompt",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=tmXpiLrw3zA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : J'ai refait Pokémon avec Claude Opus 4.8 en un seul prompt..."
    },
    {
        "id": "wb3Y1iFmEn4",
        "videoId": "wb3Y1iFmEn4",
        "title": "Carpathia: Organisez vos vidéos YouTube avec Obsidian facilement ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=wb3Y1iFmEn4",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Carpathia: Organisez vos vidéos YouTube avec Obsidian facilement ! #shorts...",
        "isShort": true
    },
    {
        "id": "L89fHYO-NOc",
        "videoId": "L89fHYO-NOc",
        "title": "Wiki LLM: Opportunités Infinies pour Votre Business et Créativité ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=L89fHYO-NOc",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Wiki LLM: Opportunités Infinies pour Votre Business et Créativité ! #shorts...",
        "isShort": true
    },
    {
        "id": "QL5zztwOOHE",
        "videoId": "QL5zztwOOHE",
        "title": "Tout comprendre sur les ports réseaux: TCP, UDP et Sockets -Maîtrise les ports réseaux: De 0 à 65535",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-30",
        "url": "https://www.youtube.com/watch?v=QL5zztwOOHE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Tout comprendre sur les ports réseaux: TCP, UDP et Sockets -Maîtrise les ports réseaux: De 0 à 65535..."
    },
    {
        "id": "woNAzDic5XQ",
        "videoId": "woNAzDic5XQ",
        "title": "Il existe 5 types d'utilisateurs IA. Et la plupart sont bloqués au niveau 2 sans le savoir. ��",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=woNAzDic5XQ",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Il existe 5 types d'utilisateurs IA. Et la plupart sont bloqués au niveau 2 sans le savoir. ��..."
    },
    {
        "id": "jqbNiDJFYYw",
        "videoId": "jqbNiDJFYYw",
        "title": "C’est quoi le fichier Claude.MD ?",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=jqbNiDJFYYw",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : C’est quoi le fichier Claude.MD ?..."
    },
    {
        "id": "Jjt23sjUelY",
        "videoId": "Jjt23sjUelY",
        "title": "Claude 4.8 orchestre 100 agents",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=Jjt23sjUelY",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Claude 4.8 orchestre 100 agents..."
    },
    {
        "id": "3QjPeY7KoV4",
        "videoId": "3QjPeY7KoV4",
        "title": "L'actualité tech du 29/05/2026 en Live sur Renaud Dékode",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=3QjPeY7KoV4",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : L'actualité tech du 29/05/2026 en Live sur Renaud Dékode..."
    },
    {
        "id": "zAYPmtbj3hk",
        "videoId": "zAYPmtbj3hk",
        "title": "Mistral envoie du lourd, Claude Opus 4.8 consolide",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=zAYPmtbj3hk",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Mistral envoie du lourd, Claude Opus 4.8 consolide..."
    },
    {
        "id": "PsYDHoTBwoQ",
        "videoId": "PsYDHoTBwoQ",
        "title": "La Chine trace tous ses robots",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=PsYDHoTBwoQ",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : La Chine trace tous ses robots..."
    },
    {
        "id": "vfeWJBbiai8",
        "videoId": "vfeWJBbiai8",
        "title": "Claude Opus 4.8 Est-il Le Nouveau Roi de l’IA ? (Test Complet)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=vfeWJBbiai8",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Claude Opus 4.8 Est-il Le Nouveau Roi de l’IA ? (Test Complet)..."
    },
    {
        "id": "sClcb1Z1i8E",
        "videoId": "sClcb1Z1i8E",
        "title": "Claude Code : Zéro Installation, Organisation Maximale avec Obsidian ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=sClcb1Z1i8E",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Claude Code : Zéro Installation, Organisation Maximale avec Obsidian ! #shorts...",
        "isShort": true
    },
    {
        "id": "Mi-eYRSfHuI",
        "videoId": "Mi-eYRSfHuI",
        "title": "Le Cerveau IA de Karpathy Révolutionne Tes Connaissances ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=Mi-eYRSfHuI",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Le Cerveau IA de Karpathy Révolutionne Tes Connaissances ! #shorts...",
        "isShort": true
    },
    {
        "id": "97ZjRo_uCho",
        "videoId": "97ZjRo_uCho",
        "title": "Comprendre les Ports Réseau - IP, Ports et Sockets: Le secret de la communication réseau",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=97ZjRo_uCho",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Comprendre les Ports Réseau - IP, Ports et Sockets: Le secret de la communication réseau..."
    },
    {
        "id": "hD-Sj_Lbx9A",
        "videoId": "hD-Sj_Lbx9A",
        "title": "L'Adresse MAC: Le Mensonge de l'Anonymat en Réseau - Arrêtez de confondre IP et MAC: La Vérité enfin",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=hD-Sj_Lbx9A",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : L'Adresse MAC: Le Mensonge de l'Anonymat en Réseau - Arrêtez de confondre IP et MAC: La Vérité enfin..."
    },
    {
        "id": "z5mGCGeMaDY",
        "videoId": "z5mGCGeMaDY",
        "title": "Actus IA : on vient de franchir un cap (un GROS !)",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-05-29",
        "url": "https://www.youtube.com/watch?v=z5mGCGeMaDY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Actus IA : on vient de franchir un cap (un GROS !)..."
    },
    {
        "id": "dcH39RAdQ5Y",
        "videoId": "dcH39RAdQ5Y",
        "title": "3 repos GitHub pour économiser jusqu'à 98% de tokens avec Claude.",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=dcH39RAdQ5Y",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 3 repos GitHub pour économiser jusqu'à 98% de tokens avec Claude...."
    },
    {
        "id": "fmv0UlVZ19E",
        "videoId": "fmv0UlVZ19E",
        "title": "Le NOUVEAU ChatGPT dans Excel vient de tout changer !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=fmv0UlVZ19E",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Le NOUVEAU ChatGPT dans Excel vient de tout changer !..."
    },
    {
        "id": "GIyyRAwVMuk",
        "videoId": "GIyyRAwVMuk",
        "title": "IA Mythos affole la BCE",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=GIyyRAwVMuk",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : IA Mythos affole la BCE..."
    },
    {
        "id": "uox9mb3uxhs",
        "videoId": "uox9mb3uxhs",
        "title": "Comment l'IA révolutionne l'accessibilité numérique, avec Julien Sauvageot",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=uox9mb3uxhs",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Comment l'IA révolutionne l'accessibilité numérique, avec Julien Sauvageot..."
    },
    {
        "id": "30ioBoxdDbM",
        "videoId": "30ioBoxdDbM",
        "title": "Cannes : un film IA en 2 semaines",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=30ioBoxdDbM",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Cannes : un film IA en 2 semaines..."
    },
    {
        "id": "mv5Sb75QLgc",
        "videoId": "mv5Sb75QLgc",
        "title": "Comment Claude Génère mes Propales à +10k€ en 10 minutes (Guide Complet)",
        "author": "Lucas Reverdy",
        "source": "@reverdybusiness",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=mv5Sb75QLgc",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Lucas Reverdy : Comment Claude Génère mes Propales à +10k€ en 10 minutes (Guide Complet)..."
    },
    {
        "id": "vunt2M-BYmI",
        "videoId": "vunt2M-BYmI",
        "title": "Rocket 1.0 : L’IA Parfaite Pour Lancer un SaaS ? (Test réel 🔥)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=vunt2M-BYmI",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Rocket 1.0 : L’IA Parfaite Pour Lancer un SaaS ? (Test réel 🔥)..."
    },
    {
        "id": "ZSoi6C6jOEA",
        "videoId": "ZSoi6C6jOEA",
        "title": "Hermes Agent : 3 use cases que PERSONNE n'a testés 🤖",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=ZSoi6C6jOEA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Hermes Agent : 3 use cases que PERSONNE n'a testés 🤖..."
    },
    {
        "id": "G-Tjz_hC1L4",
        "videoId": "G-Tjz_hC1L4",
        "title": "Construire des Agents IA Vocaux n'a jamais été aussi facile (GROK + CLAUDE CODE )",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=G-Tjz_hC1L4",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Construire des Agents IA Vocaux n'a jamais été aussi facile (GROK + CLAUDE CODE )..."
    },
    {
        "id": "67KzWdV6EzE",
        "videoId": "67KzWdV6EzE",
        "title": "C'est quoi une adresse IP? - Comprendre l'adresse IP: Le guide complet pour débutants",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-28",
        "url": "https://www.youtube.com/watch?v=67KzWdV6EzE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : C'est quoi une adresse IP? - Comprendre l'adresse IP: Le guide complet pour débutants..."
    },
    {
        "id": "gXm3Go03l_s",
        "videoId": "gXm3Go03l_s",
        "title": "J'ai codé une IA qui fait mes miniatures (c'est dingue)",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-05-27",
        "url": "https://www.youtube.com/watch?v=gXm3Go03l_s",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : J'ai codé une IA qui fait mes miniatures (c'est dingue)..."
    },
    {
        "id": "Qgq9-8VVgpc",
        "videoId": "Qgq9-8VVgpc",
        "title": "La Chine est plus en avance sur l’IA que vous le pensez…",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-27",
        "url": "https://www.youtube.com/watch?v=Qgq9-8VVgpc",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : La Chine est plus en avance sur l’IA que vous le pensez…..."
    },
    {
        "id": "j-2LJqScwFo",
        "videoId": "j-2LJqScwFo",
        "title": "IA : la France lance sa Gigafactory",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-27",
        "url": "https://www.youtube.com/watch?v=j-2LJqScwFo",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : IA : la France lance sa Gigafactory..."
    },
    {
        "id": "hw5b4M0IoBY",
        "videoId": "hw5b4M0IoBY",
        "title": "IA : La France se rebelle et l'Europe flippe",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-27",
        "url": "https://www.youtube.com/watch?v=hw5b4M0IoBY",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : IA : La France se rebelle et l'Europe flippe..."
    },
    {
        "id": "R228lKS3n3I",
        "videoId": "R228lKS3n3I",
        "title": "L'actualité tech du 27/05/2026 en Live sur Renaud Dékode",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-27",
        "url": "https://www.youtube.com/watch?v=R228lKS3n3I",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : L'actualité tech du 27/05/2026 en Live sur Renaud Dékode..."
    },
    {
        "id": "rfMEwbtOp_c",
        "videoId": "rfMEwbtOp_c",
        "title": "Google rend Street View jouable",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-27",
        "url": "https://www.youtube.com/watch?v=rfMEwbtOp_c",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Google rend Street View jouable..."
    },
    {
        "id": "MjCJIJ4PuSw",
        "videoId": "MjCJIJ4PuSw",
        "title": "J'ai étudié les LLM pendant 6 mois (et j'ai enfin compris comment ChatGPT fonctionne)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-05-27",
        "url": "https://www.youtube.com/watch?v=MjCJIJ4PuSw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : J'ai étudié les LLM pendant 6 mois (et j'ai enfin compris comment ChatGPT fonctionne)..."
    },
    {
        "id": "luQNxwS1yc8",
        "videoId": "luQNxwS1yc8",
        "title": "Pourquoi DeepSeek Va Changer L’avenir Des Agents IA à Jamais 🐳",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-27",
        "url": "https://www.youtube.com/watch?v=luQNxwS1yc8",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Pourquoi DeepSeek Va Changer L’avenir Des Agents IA à Jamais 🐳..."
    },
    {
        "id": "9ySW-tzoDpU",
        "videoId": "9ySW-tzoDpU",
        "title": "Réponses IA : comment passer de ça... à ÇA !",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-05-27",
        "url": "https://www.youtube.com/watch?v=9ySW-tzoDpU",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Réponses IA : comment passer de ça... à ÇA !..."
    },
    {
        "id": "BZA2kdEeODI",
        "videoId": "BZA2kdEeODI",
        "title": "Qu’est-ce que le MCP ?",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-26",
        "url": "https://www.youtube.com/watch?v=BZA2kdEeODI",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Qu’est-ce que le MCP ?..."
    },
    {
        "id": "OZo57C9nohk",
        "videoId": "OZo57C9nohk",
        "title": "Le créateur de Claude Code réserve tous ses vols et hôtels avec Cowork",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-26",
        "url": "https://www.youtube.com/watch?v=OZo57C9nohk",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Le créateur de Claude Code réserve tous ses vols et hôtels avec Cowork..."
    },
    {
        "id": "49p-4CRX0y4",
        "videoId": "49p-4CRX0y4",
        "title": "IA Alibaba: 35h sans s’arrêter",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-26",
        "url": "https://www.youtube.com/watch?v=49p-4CRX0y4",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : IA Alibaba: 35h sans s’arrêter..."
    },
    {
        "id": "9KvncVTC6zU",
        "videoId": "9KvncVTC6zU",
        "title": "Claude Opus 4.8 : Pourquoi Claude Code Ne Sera Plus Le Même (LEAK)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-26",
        "url": "https://www.youtube.com/watch?v=9KvncVTC6zU",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Claude Opus 4.8 : Pourquoi Claude Code Ne Sera Plus Le Même (LEAK)..."
    },
    {
        "id": "njFew6knQUY",
        "videoId": "njFew6knQUY",
        "title": "Comment fonctionne l'adresse MAC? (WiFi, Ethernet, Bluetooth) - Adresse MAC vs Adresse IP",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-26",
        "url": "https://www.youtube.com/watch?v=njFew6knQUY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Comment fonctionne l'adresse MAC? (WiFi, Ethernet, Bluetooth) - Adresse MAC vs Adresse IP..."
    },
    {
        "id": "tCuJ4gjV3e4",
        "videoId": "tCuJ4gjV3e4",
        "title": "IPO SpaceX et OpenAI : choc",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-05-25",
        "url": "https://www.youtube.com/watch?v=tCuJ4gjV3e4",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : IPO SpaceX et OpenAI : choc..."
    },
    {
        "id": "Y1oeYrm2C6w",
        "videoId": "Y1oeYrm2C6w",
        "title": "Comprendre l'Adresse IP: IPv4, IPv6 et Adresse MAC expliqués - Ne faites plus jamais la confusion!",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-25",
        "url": "https://www.youtube.com/watch?v=Y1oeYrm2C6w",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Comprendre l'Adresse IP: IPv4, IPv6 et Adresse MAC expliqués - Ne faites plus jamais la confusion!..."
    },
    {
        "id": "yS7zBSvI0Y8",
        "videoId": "yS7zBSvI0Y8",
        "title": "Google I/O 2026 : les 5 outils que vous allez utiliser tous les jours",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-05-25",
        "url": "https://www.youtube.com/watch?v=yS7zBSvI0Y8",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Google I/O 2026 : les 5 outils que vous allez utiliser tous les jours..."
    },
    {
        "id": "jNYq99U5gR4",
        "videoId": "jNYq99U5gR4",
        "title": "Tu savais que Claude Code avait une barre de statut cachée ?",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-24",
        "url": "https://www.youtube.com/watch?v=jNYq99U5gR4",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Tu savais que Claude Code avait une barre de statut cachée ?..."
    },
    {
        "id": "y4AAFTlA6ak",
        "videoId": "y4AAFTlA6ak",
        "title": "Claude Skills : Tout le monde peut ENFIN automatiser !",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-05-24",
        "url": "https://www.youtube.com/watch?v=y4AAFTlA6ak",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Claude Skills : Tout le monde peut ENFIN automatiser !..."
    },
    {
        "id": "i0iU1iFXAfA",
        "videoId": "i0iU1iFXAfA",
        "title": "J'ai économisé 80% de tokens sur Claude Code sans toucher une seule ligne de code.",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-23",
        "url": "https://www.youtube.com/watch?v=i0iU1iFXAfA",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : J'ai économisé 80% de tokens sur Claude Code sans toucher une seule ligne de code...."
    },
    {
        "id": "m7bYnWcx8s0",
        "videoId": "m7bYnWcx8s0",
        "title": "200 entrepreneurs, 21 hectares, 4 jours",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-05-23",
        "url": "https://www.youtube.com/watch?v=m7bYnWcx8s0",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : 200 entrepreneurs, 21 hectares, 4 jours..."
    },
    {
        "id": "f6EmBdBa1hI",
        "videoId": "f6EmBdBa1hI",
        "title": "Comment fonctionne le WiFi? Tout comprendre - Tout savoir sur le WiFi: Points d'accès Box et Réseaux",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-23",
        "url": "https://www.youtube.com/watch?v=f6EmBdBa1hI",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Comment fonctionne le WiFi? Tout comprendre - Tout savoir sur le WiFi: Points d'accès Box et Réseaux..."
    },
    {
        "id": "H6ImtTHK9wA",
        "videoId": "H6ImtTHK9wA",
        "title": "WiFi vs Internet: La différence que tu dois connaître - 2.4 GHz vs 5 GHz: Quelle fréquence choisir?",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-23",
        "url": "https://www.youtube.com/watch?v=H6ImtTHK9wA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : WiFi vs Internet: La différence que tu dois connaître - 2.4 GHz vs 5 GHz: Quelle fréquence choisir?..."
    },
    {
        "id": "6vq00uTyYu8",
        "videoId": "6vq00uTyYu8",
        "title": "La seule certification IA qui vaut vraiment quelque chose en 2026.",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-22",
        "url": "https://www.youtube.com/watch?v=6vq00uTyYu8",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : La seule certification IA qui vaut vraiment quelque chose en 2026...."
    },
    {
        "id": "ReO0rVllZIk",
        "videoId": "ReO0rVllZIk",
        "title": "Ethernet vs Wi-Fi vs Internet: Quelles Différences? - Comprendre le Réseau Ethernet: La Base du LAN",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-22",
        "url": "https://www.youtube.com/watch?v=ReO0rVllZIk",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Ethernet vs Wi-Fi vs Internet: Quelles Différences? - Comprendre le Réseau Ethernet: La Base du LAN..."
    },
    {
        "id": "q7ShYQYNVI8",
        "videoId": "q7ShYQYNVI8",
        "title": "Comment fonctionne Internet? Le voyage de vos données - Comprendre le réseau: IP, MAC et Ports",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-22",
        "url": "https://www.youtube.com/watch?v=q7ShYQYNVI8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Comment fonctionne Internet? Le voyage de vos données - Comprendre le réseau: IP, MAC et Ports..."
    },
    {
        "id": "VMUDRIYRoQs",
        "videoId": "VMUDRIYRoQs",
        "title": "Actus IA : Google dégaine... ChatGPT et Claude ripostent !",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-05-22",
        "url": "https://www.youtube.com/watch?v=VMUDRIYRoQs",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Actus IA : Google dégaine... ChatGPT et Claude ripostent !..."
    },
    {
        "id": "KxkxqmRNndU",
        "videoId": "KxkxqmRNndU",
        "title": "Connecte Claude directement à ton compte Instagram !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=KxkxqmRNndU",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Connecte Claude directement à ton compte Instagram !..."
    },
    {
        "id": "9j6ecsEpZks",
        "videoId": "9j6ecsEpZks",
        "title": "Le directeur de Gemini vient de publier un repo GitHub qui devient viral.",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=9j6ecsEpZks",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Le directeur de Gemini vient de publier un repo GitHub qui devient viral...."
    },
    {
        "id": "o3-6jJvOpjI",
        "videoId": "o3-6jJvOpjI",
        "title": "Codex est devenu INCROYABLE... 7 Exemples concrets !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=o3-6jJvOpjI",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Codex est devenu INCROYABLE... 7 Exemples concrets !..."
    },
    {
        "id": "0AEsQYXHAmY",
        "videoId": "0AEsQYXHAmY",
        "title": "Créer un vrai SaaS avec l’IA en 2026 : Tuto Complet Hostinger Horizons 😱🔥",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=0AEsQYXHAmY",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Créer un vrai SaaS avec l’IA en 2026 : Tuto Complet Hostinger Horizons 😱🔥..."
    },
    {
        "id": "ULlBUO1dAQ4",
        "videoId": "ULlBUO1dAQ4",
        "title": "Claude Design vs Figma : j'ai recréé Apple.com pour comparer",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=ULlBUO1dAQ4",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Claude Design vs Figma : j'ai recréé Apple.com pour comparer..."
    },
    {
        "id": "F74GXOsWEiE",
        "videoId": "F74GXOsWEiE",
        "title": "IA: Code Sudoku HTML Hors Ligne en Secondes! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=F74GXOsWEiE",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : IA: Code Sudoku HTML Hors Ligne en Secondes! #shorts...",
        "isShort": true
    },
    {
        "id": "-6PHej38buw",
        "videoId": "-6PHej38buw",
        "title": "Le co-fondateur d'OpenAI vient de changer Claude Code pour toujours (LLM Wiki)",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=-6PHej38buw",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Le co-fondateur d'OpenAI vient de changer Claude Code pour toujours (LLM Wiki)..."
    },
    {
        "id": "BZgiYCH65ho",
        "videoId": "BZgiYCH65ho",
        "title": "Ollama + Claude Code : Une machine de guerre est nécessaire ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=BZgiYCH65ho",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Ollama + Claude Code : Une machine de guerre est nécessaire ! #shorts...",
        "isShort": true
    },
    {
        "id": "OasQ954W4D8",
        "videoId": "OasQ954W4D8",
        "title": "IP vs MAC: L'erreur fatale que tout le monde commet - Comprendre le Voyage Invisible de nos Données",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=OasQ954W4D8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : IP vs MAC: L'erreur fatale que tout le monde commet - Comprendre le Voyage Invisible de nos Données..."
    },
    {
        "id": "LrG377qQlVw",
        "videoId": "LrG377qQlVw",
        "title": "Modèle OSI vs TCP/IP: Tout comprendre en 3 minutes",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-21",
        "url": "https://www.youtube.com/watch?v=LrG377qQlVw",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Modèle OSI vs TCP/IP: Tout comprendre en 3 minutes..."
    },
    {
        "id": "NU3G3RHuIX8",
        "videoId": "NU3G3RHuIX8",
        "title": "N'importe qui peut coder ? Ce gérant de salle d’escalade en est la PREUVE !",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-05-20",
        "url": "https://www.youtube.com/watch?v=NU3G3RHuIX8",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : N'importe qui peut coder ? Ce gérant de salle d’escalade en est la PREUVE !..."
    },
    {
        "id": "XCWlHH8iMqU",
        "videoId": "XCWlHH8iMqU",
        "title": "Anthropic vient de lancer un pack complet pour les petites entreprises",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-20",
        "url": "https://www.youtube.com/watch?v=XCWlHH8iMqU",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Anthropic vient de lancer un pack complet pour les petites entreprises..."
    },
    {
        "id": "6sgCPGojZTA",
        "videoId": "6sgCPGojZTA",
        "title": "Le prompt à toujours utiliser dans Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-05-20",
        "url": "https://www.youtube.com/watch?v=6sgCPGojZTA",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Le prompt à toujours utiliser dans Claude !..."
    },
    {
        "id": "B9zUxH3umHQ",
        "videoId": "B9zUxH3umHQ",
        "title": "Gemini 3.5 Flash : Le modèle le plus rapide de l’histoire ? (290 tokens/s)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-20",
        "url": "https://www.youtube.com/watch?v=B9zUxH3umHQ",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Gemini 3.5 Flash : Le modèle le plus rapide de l’histoire ? (290 tokens/s)..."
    },
    {
        "id": "9BnO43ijZwE",
        "videoId": "9BnO43ijZwE",
        "title": "Qwen 3.7 est la !",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-20",
        "url": "https://www.youtube.com/watch?v=9BnO43ijZwE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Qwen 3.7 est la !..."
    },
    {
        "id": "AdFp_9DktUg",
        "videoId": "AdFp_9DktUg",
        "title": "Téléchargez des modèles IA facilement avec Ollama ! 🚀 #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-20",
        "url": "https://www.youtube.com/watch?v=AdFp_9DktUg",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Téléchargez des modèles IA facilement avec Ollama ! 🚀 #shorts...",
        "isShort": true
    },
    {
        "id": "LXImtt7MgNE",
        "videoId": "LXImtt7MgNE",
        "title": "Ollama : Le lancement qui fait des siennes #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-20",
        "url": "https://www.youtube.com/watch?v=LXImtt7MgNE",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Ollama : Le lancement qui fait des siennes #shorts...",
        "isShort": true
    },
    {
        "id": "xFs7A_fEFa4",
        "videoId": "xFs7A_fEFa4",
        "title": "Ce site te donne accès à des centaines d’outils IA gratuitement",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-19",
        "url": "https://www.youtube.com/watch?v=xFs7A_fEFa4",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Ce site te donne accès à des centaines d’outils IA gratuitement..."
    },
    {
        "id": "flZ8Etn_N8E",
        "videoId": "flZ8Etn_N8E",
        "title": "Arrête de payer pour ElevenLabs",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-05-19",
        "url": "https://www.youtube.com/watch?v=flZ8Etn_N8E",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Arrête de payer pour ElevenLabs..."
    },
    {
        "id": "UD-p0mPV38A",
        "videoId": "UD-p0mPV38A",
        "title": "Qwen 3.7 Max : Pourquoi Claude Devrait Commencer à S’inquiéter",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-19",
        "url": "https://www.youtube.com/watch?v=UD-p0mPV38A",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Qwen 3.7 Max : Pourquoi Claude Devrait Commencer à S’inquiéter..."
    },
    {
        "id": "6FPbsQnDYCM",
        "videoId": "6FPbsQnDYCM",
        "title": "Ollama: Les Modèles IA qui Tournent sur VOTRE PC ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-19",
        "url": "https://www.youtube.com/watch?v=6FPbsQnDYCM",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Ollama: Les Modèles IA qui Tournent sur VOTRE PC ! #shorts...",
        "isShort": true
    },
    {
        "id": "Xle7whxjTcc",
        "videoId": "Xle7whxjTcc",
        "title": "Télécharge tes modèles IA avec Ollama : Productivité Offline Assurée ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-19",
        "url": "https://www.youtube.com/watch?v=Xle7whxjTcc",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Télécharge tes modèles IA avec Ollama : Productivité Offline Assurée ! #shorts...",
        "isShort": true
    },
    {
        "id": "jY7Bp-m7X1U",
        "videoId": "jY7Bp-m7X1U",
        "title": "Modèle OSI vs TCP/IP: Les différences enfin expliquées",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-19",
        "url": "https://www.youtube.com/watch?v=jY7Bp-m7X1U",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Modèle OSI vs TCP/IP: Les différences enfin expliquées..."
    },
    {
        "id": "wjFdqDyTz3s",
        "videoId": "wjFdqDyTz3s",
        "title": "J'ai créé 35 pubs vidéo en 1 minute avec Claude (Tuto MCP)",
        "author": "Aurélien Fagioli",
        "source": "@AurelienAutomatisation",
        "date": "2026-05-19",
        "url": "https://www.youtube.com/watch?v=wjFdqDyTz3s",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Aurélien Fagioli : J'ai créé 35 pubs vidéo en 1 minute avec Claude (Tuto MCP)..."
    },
    {
        "id": "b5HDUbwcgzo",
        "videoId": "b5HDUbwcgzo",
        "title": "Cet outil peut remplacer 100€ d’abonnements IA pour 8$ ?",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-18",
        "url": "https://www.youtube.com/watch?v=b5HDUbwcgzo",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Cet outil peut remplacer 100€ d’abonnements IA pour 8$ ?..."
    },
    {
        "id": "-tPJLy0hqxQ",
        "videoId": "-tPJLy0hqxQ",
        "title": "L'IA Révolutionne Vos Réseaux Sociaux avec Claude Code &amp; Vibe Socials #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-18",
        "url": "https://www.youtube.com/watch?v=-tPJLy0hqxQ",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : L'IA Révolutionne Vos Réseaux Sociaux avec Claude Code &amp; Vibe Socials #shorts...",
        "isShort": true
    },
    {
        "id": "8kLeL9OERPU",
        "videoId": "8kLeL9OERPU",
        "title": "Installez Ollama Facilement sur Votre PC: Le Futur est Là ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-18",
        "url": "https://www.youtube.com/watch?v=8kLeL9OERPU",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Installez Ollama Facilement sur Votre PC: Le Futur est Là ! #shorts...",
        "isShort": true
    },
    {
        "id": "GFZXeKKyac8",
        "videoId": "GFZXeKKyac8",
        "title": "Comprendre le Modèle TCP/IP: Comment fonctionne Internet?",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-18",
        "url": "https://www.youtube.com/watch?v=GFZXeKKyac8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Comprendre le Modèle TCP/IP: Comment fonctionne Internet?..."
    },
    {
        "id": "ZfOCoTnpymA",
        "videoId": "ZfOCoTnpymA",
        "title": "Divise ta facture Claude Code par 10 avec ce nouvel outil (Tuto Complet)",
        "author": "Baptiste Simard - IA",
        "source": "@BaptIA",
        "date": "2026-05-18",
        "url": "https://www.youtube.com/watch?v=ZfOCoTnpymA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Baptiste Simard - IA : Divise ta facture Claude Code par 10 avec ce nouvel outil (Tuto Complet)..."
    },
    {
        "id": "tWneZs6ttSA",
        "videoId": "tWneZs6ttSA",
        "title": "Canva : tous les raccourcis et réglages pour gagner 1h chaque semaine",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-05-18",
        "url": "https://www.youtube.com/watch?v=tWneZs6ttSA",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Canva : tous les raccourcis et réglages pour gagner 1h chaque semaine..."
    },
    {
        "id": "T7vTh4StDZM",
        "videoId": "T7vTh4StDZM",
        "title": "Comment devenir quelqu'un d'autre pour créer sa chance",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-05-17",
        "url": "https://www.youtube.com/watch?v=T7vTh4StDZM",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment devenir quelqu'un d'autre pour créer sa chance..."
    },
    {
        "id": "oS1RvuLPGbA",
        "videoId": "oS1RvuLPGbA",
        "title": "Comment Créer Sans Limite avec l’IA: Formation Claude Code (2026) | Guide Complet Débutant",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-05-17",
        "url": "https://www.youtube.com/watch?v=oS1RvuLPGbA",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comment Créer Sans Limite avec l’IA: Formation Claude Code (2026) | Guide Complet Débutant..."
    },
    {
        "id": "JntQOBm7-44",
        "videoId": "JntQOBm7-44",
        "title": "Trouve le MEILLEUR modèle IA pour ton PC avec Ollama ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-05-17",
        "url": "https://www.youtube.com/watch?v=JntQOBm7-44",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Trouve le MEILLEUR modèle IA pour ton PC avec Ollama ! #shorts...",
        "isShort": true
    },
    {
        "id": "A5LozqMdv5I",
        "videoId": "A5LozqMdv5I",
        "title": "Comprendre le Modèle OSI: Les 7 Couches Expliquées Simplement",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-05-17",
        "url": "https://www.youtube.com/watch?v=A5LozqMdv5I",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Comprendre le Modèle OSI: Les 7 Couches Expliquées Simplement..."
    },
    {
        "id": "q5IfMPw6mFg",
        "videoId": "q5IfMPw6mFg",
        "title": "Ce dev gère 4 agents IA comme une équipe d'ingénieurs - co-fondateur d'Argil.AI (YC)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-05-16",
        "url": "https://www.youtube.com/watch?v=q5IfMPw6mFg",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Ce dev gère 4 agents IA comme une équipe d'ingénieurs - co-fondateur d'Argil.AI (YC)..."
    },
    {
        "id": "m0tqhlkr2pw",
        "videoId": "m0tqhlkr2pw",
        "title": "GPT 5.5 Instant : OpenAI admet un vrai problème",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-15",
        "url": "https://www.youtube.com/watch?v=m0tqhlkr2pw",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : GPT 5.5 Instant : OpenAI admet un vrai problème..."
    },
    {
        "id": "9nXqUad7x9o",
        "videoId": "9nXqUad7x9o",
        "title": "Actus IA : ChatGPT, Gemini, Claude... du nouveau PARTOUT !",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-05-15",
        "url": "https://www.youtube.com/watch?v=9nXqUad7x9o",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Actus IA : ChatGPT, Gemini, Claude... du nouveau PARTOUT !..."
    },
    {
        "id": "aQ3DckyO4eE",
        "videoId": "aQ3DckyO4eE",
        "title": "TicNote Cloud : Le Meilleur Outil IA pour Tes Réunions ? (Test Complet) 😱🔥",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-14",
        "url": "https://www.youtube.com/watch?v=aQ3DckyO4eE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : TicNote Cloud : Le Meilleur Outil IA pour Tes Réunions ? (Test Complet) 😱🔥..."
    },
    {
        "id": "uHHYXQZzNSM",
        "videoId": "uHHYXQZzNSM",
        "title": "J'ai remplacé mon monteur vidéo par Claude (voici le workflow exact)",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-05-14",
        "url": "https://www.youtube.com/watch?v=uHHYXQZzNSM",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : J'ai remplacé mon monteur vidéo par Claude (voici le workflow exact)..."
    },
    {
        "id": "cY9h0zre4dI",
        "videoId": "cY9h0zre4dI",
        "title": "L’AIOS va me remplacer. Guide Claude Code AGENTIC OS",
        "author": "Baptiste Simard - IA",
        "source": "@BaptIA",
        "date": "2026-05-14",
        "url": "https://www.youtube.com/watch?v=cY9h0zre4dI",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Baptiste Simard - IA : L’AIOS va me remplacer. Guide Claude Code AGENTIC OS..."
    },
    {
        "id": "JOPrKZheAc4",
        "videoId": "JOPrKZheAc4",
        "title": "J'ai arrêté d'utiliser OpenClaw (je t'explique pourquoi)",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-05-13",
        "url": "https://www.youtube.com/watch?v=JOPrKZheAc4",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : J'ai arrêté d'utiliser OpenClaw (je t'explique pourquoi)..."
    },
    {
        "id": "PxthwNWLV_E",
        "videoId": "PxthwNWLV_E",
        "title": "Mon classement des fonctionnalités dans Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-05-13",
        "url": "https://www.youtube.com/watch?v=PxthwNWLV_E",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Mon classement des fonctionnalités dans Claude !..."
    },
    {
        "id": "Z678vGFryxE",
        "videoId": "Z678vGFryxE",
        "title": "Hermes Agent Desktop : Le Premier Agent IA 24/7Qui Évolue Tout Seul ? 😱🔥",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-13",
        "url": "https://www.youtube.com/watch?v=Z678vGFryxE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Hermes Agent Desktop : Le Premier Agent IA 24/7Qui Évolue Tout Seul ? 😱🔥..."
    },
    {
        "id": "dyZjwf1GeYk",
        "videoId": "dyZjwf1GeYk",
        "title": "Anthropic vient de simplifier ENORMEMENT la gestion d’agents!",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-05-12",
        "url": "https://www.youtube.com/watch?v=dyZjwf1GeYk",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Anthropic vient de simplifier ENORMEMENT la gestion d’agents!..."
    },
    {
        "id": "YCttZsEIuqI",
        "videoId": "YCttZsEIuqI",
        "title": "Il a connecté son ADN et sa montre à l'IA (le résultat est génial)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-05-11",
        "url": "https://www.youtube.com/watch?v=YCttZsEIuqI",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Il a connecté son ADN et sa montre à l'IA (le résultat est génial)..."
    },
    {
        "id": "Z9-B4hSu-3o",
        "videoId": "Z9-B4hSu-3o",
        "title": "DeepSeek V4 Détruit Les IA à Plusieurs Milliards…Gratuitement ? 🤔",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-11",
        "url": "https://www.youtube.com/watch?v=Z9-B4hSu-3o",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : DeepSeek V4 Détruit Les IA à Plusieurs Milliards…Gratuitement ? 🤔..."
    },
    {
        "id": "mfkp0t85nKQ",
        "videoId": "mfkp0t85nKQ",
        "title": "Arrêtez les mauvais diapos | Voici la méthode qui marche",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-05-11",
        "url": "https://www.youtube.com/watch?v=mfkp0t85nKQ",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Arrêtez les mauvais diapos | Voici la méthode qui marche..."
    },
    {
        "id": "J4hyyVkt_Bo",
        "videoId": "J4hyyVkt_Bo",
        "title": "Les Services IA à 3k€ minimum que les PME achètent vraiment (comment les trouver)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-05-10",
        "url": "https://www.youtube.com/watch?v=J4hyyVkt_Bo",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Les Services IA à 3k€ minimum que les PME achètent vraiment (comment les trouver)..."
    },
    {
        "id": "w2JE7HUNJFU",
        "videoId": "w2JE7HUNJFU",
        "title": "5 Hacks Pour Utiliser Claude IA mieux que 99% de la Population",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-05-10",
        "url": "https://www.youtube.com/watch?v=w2JE7HUNJFU",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : 5 Hacks Pour Utiliser Claude IA mieux que 99% de la Population..."
    },
    {
        "id": "y0taBHJRJXY",
        "videoId": "y0taBHJRJXY",
        "title": "Ce plombier a un meilleur système IA que la plupart des devs",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-05-09",
        "url": "https://www.youtube.com/watch?v=y0taBHJRJXY",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Ce plombier a un meilleur système IA que la plupart des devs..."
    },
    {
        "id": "diCd1Y-QUtk",
        "videoId": "diCd1Y-QUtk",
        "title": "i10X : Peut-il remplacer 100€ d’abonnements IA pour 8€ ? 😱",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-09",
        "url": "https://www.youtube.com/watch?v=diCd1Y-QUtk",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : i10X : Peut-il remplacer 100€ d’abonnements IA pour 8€ ? 😱..."
    },
    {
        "id": "3UVbXmUIBSk",
        "videoId": "3UVbXmUIBSk",
        "title": "Comment TOUT Automatiser en 1 Prompt | de A à Z (Claude Code + n8n) !",
        "author": "Aurélien Fagioli",
        "source": "@AurelienAutomatisation",
        "date": "2026-05-09",
        "url": "https://www.youtube.com/watch?v=3UVbXmUIBSk",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Aurélien Fagioli : Comment TOUT Automatiser en 1 Prompt | de A à Z (Claude Code + n8n) !..."
    },
    {
        "id": "SgxSUle-TcE",
        "videoId": "SgxSUle-TcE",
        "title": "Créer son système IA : ça vaut encore le coup ?",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-05-08",
        "url": "https://www.youtube.com/watch?v=SgxSUle-TcE",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Créer son système IA : ça vaut encore le coup ?..."
    },
    {
        "id": "NCvARWY-_aQ",
        "videoId": "NCvARWY-_aQ",
        "title": "Ne plus JAMAIS atteindre la limite de Tokens dans Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-05-07",
        "url": "https://www.youtube.com/watch?v=NCvARWY-_aQ",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Ne plus JAMAIS atteindre la limite de Tokens dans Claude !..."
    },
    {
        "id": "sXGDheIjn6w",
        "videoId": "sXGDheIjn6w",
        "title": "Xiaomi MiMo V2.5 PRO : Le Monstre Open Source (10x moins cher que Claude)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-05-07",
        "url": "https://www.youtube.com/watch?v=sXGDheIjn6w",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Xiaomi MiMo V2.5 PRO : Le Monstre Open Source (10x moins cher que Claude)..."
    },
    {
        "id": "pb8pza8dmCg",
        "videoId": "pb8pza8dmCg",
        "title": "Mon IA prospecte à ma place 24h/24 (je te DONNE le système) 🤖",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-05-07",
        "url": "https://www.youtube.com/watch?v=pb8pza8dmCg",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Mon IA prospecte à ma place 24h/24 (je te DONNE le système) 🤖..."
    },
    {
        "id": "Sz7pWrYWpHs",
        "videoId": "Sz7pWrYWpHs",
        "title": "Passer de ChatGPT à Gemini sans RIEN perdre (Tuto Complet)",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-05-07",
        "url": "https://www.youtube.com/watch?v=Sz7pWrYWpHs",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Passer de ChatGPT à Gemini sans RIEN perdre (Tuto Complet)..."
    },
    {
        "id": "o2e8yZtmxIA",
        "videoId": "o2e8yZtmxIA",
        "title": "Claude Design : c'est ILLÉGAL d'être aussi puissant",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-05-06",
        "url": "https://www.youtube.com/watch?v=o2e8yZtmxIA",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : Claude Design : c'est ILLÉGAL d'être aussi puissant..."
    },
    {
        "id": "L3YfsM5RTJs",
        "videoId": "L3YfsM5RTJs",
        "title": "Ces 5 outils + Claude Code = 9.800€/mois en 2026 (spécial débutant)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-05-06",
        "url": "https://www.youtube.com/watch?v=L3YfsM5RTJs",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Ces 5 outils + Claude Code = 9.800€/mois en 2026 (spécial débutant)..."
    },
    {
        "id": "iEeaHdbNPcw",
        "videoId": "iEeaHdbNPcw",
        "title": "5 faits secrets sur ChatGPT que personne ne connaît !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-05-06",
        "url": "https://www.youtube.com/watch?v=iEeaHdbNPcw",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : 5 faits secrets sur ChatGPT que personne ne connaît !..."
    },
    {
        "id": "g2PdHA-1Lho",
        "videoId": "g2PdHA-1Lho",
        "title": "Le plan machiavélique d'Anthropic (et comment s'en protéger)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-05-06",
        "url": "https://www.youtube.com/watch?v=g2PdHA-1Lho",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le plan machiavélique d'Anthropic (et comment s'en protéger)..."
    },
    {
        "id": "KPc5qTqTn1o",
        "videoId": "KPc5qTqTn1o",
        "title": "Une IA par tâche : la méthode qui m'a fait arrêter ChatGPT",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-05-04",
        "url": "https://www.youtube.com/watch?v=KPc5qTqTn1o",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Une IA par tâche : la méthode qui m'a fait arrêter ChatGPT..."
    },
    {
        "id": "z47n9g-QJOc",
        "videoId": "z47n9g-QJOc",
        "title": "Ta dernière chance de devenir riche avant 2027.",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-05-03",
        "url": "https://www.youtube.com/watch?v=z47n9g-QJOc",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Ta dernière chance de devenir riche avant 2027...."
    },
    {
        "id": "f31RvRfWSXc",
        "videoId": "f31RvRfWSXc",
        "title": "Comment Devenir Dangereusement Intelligent (avec l’IA)",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-05-03",
        "url": "https://www.youtube.com/watch?v=f31RvRfWSXc",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comment Devenir Dangereusement Intelligent (avec l’IA)..."
    },
    {
        "id": "mn7RcxKSddc",
        "videoId": "mn7RcxKSddc",
        "title": "Construire un second cerveau n'a jamais été aussi simple (Claude Code + Obsidian)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-05-03",
        "url": "https://www.youtube.com/watch?v=mn7RcxKSddc",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Construire un second cerveau n'a jamais été aussi simple (Claude Code + Obsidian)..."
    },
    {
        "id": "2k7qP8oXFmw",
        "videoId": "2k7qP8oXFmw",
        "title": "Crée ta base de connaissance en 5 min! (Claude Code + Obsidian)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-05-03",
        "url": "https://www.youtube.com/watch?v=2k7qP8oXFmw",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Crée ta base de connaissance en 5 min! (Claude Code + Obsidian)..."
    },
    {
        "id": "DjODUUu_QrE",
        "videoId": "DjODUUu_QrE",
        "title": "Le NOUVEL outil SECRET de Google (100% Gratuit) 🤯 #astuce",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-05-03",
        "url": "https://www.youtube.com/watch?v=DjODUUu_QrE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Le NOUVEL outil SECRET de Google (100% Gratuit) 🤯 #astuce..."
    },
    {
        "id": "IubQUC9TL2w",
        "videoId": "IubQUC9TL2w",
        "title": "L'IA devient simple avec un Second Cerveau IA (cours complet)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-05-02",
        "url": "https://www.youtube.com/watch?v=IubQUC9TL2w",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : L'IA devient simple avec un Second Cerveau IA (cours complet)..."
    },
    {
        "id": "vJNI-NyacCg",
        "videoId": "vJNI-NyacCg",
        "title": "Maîtriser 95% de Claude Design en 21 min !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-04-30",
        "url": "https://www.youtube.com/watch?v=vJNI-NyacCg",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Maîtriser 95% de Claude Design en 21 min !..."
    },
    {
        "id": "3eMkVtKNtEU",
        "videoId": "3eMkVtKNtEU",
        "title": "OpenClaw trade à ma place pendant 7 jours  (+1200$) 🤯",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-04-30",
        "url": "https://www.youtube.com/watch?v=3eMkVtKNtEU",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : OpenClaw trade à ma place pendant 7 jours  (+1200$) 🤯..."
    },
    {
        "id": "ioJMtQ8OOWw",
        "videoId": "ioJMtQ8OOWw",
        "title": "Les 5 skills à AVOIR dans ton Claude Code",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-04-29",
        "url": "https://www.youtube.com/watch?v=ioJMtQ8OOWw",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : Les 5 skills à AVOIR dans ton Claude Code..."
    },
    {
        "id": "7cTenhHWfsk",
        "videoId": "7cTenhHWfsk",
        "title": "La vérit�� sur les agents IA que personne n'ose vous dire",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-04-29",
        "url": "https://www.youtube.com/watch?v=7cTenhHWfsk",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : La vérit�� sur les agents IA que personne n'ose vous dire..."
    },
    {
        "id": "PjaygN19Udc",
        "videoId": "PjaygN19Udc",
        "title": "Comment écrire avec l'IA ? – Formation Complète",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-04-29",
        "url": "https://www.youtube.com/watch?v=PjaygN19Udc",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Comment écrire avec l'IA ? – Formation Complète..."
    },
    {
        "id": "REiHTKMFDSI",
        "videoId": "REiHTKMFDSI",
        "title": "5 Hacks pour économiser tes Tokens dans Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-04-28",
        "url": "https://www.youtube.com/watch?v=REiHTKMFDSI",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : 5 Hacks pour économiser tes Tokens dans Claude !..."
    },
    {
        "id": "lMsM3SmfTuY",
        "videoId": "lMsM3SmfTuY",
        "title": "Créer un court métrage gratuit avec l'IA (TUTO COMPLET)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-04-27",
        "url": "https://www.youtube.com/watch?v=lMsM3SmfTuY",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Créer un court métrage gratuit avec l'IA (TUTO COMPLET)..."
    },
    {
        "id": "iZnp0kQ_NnY",
        "videoId": "iZnp0kQ_NnY",
        "title": "Comment faire 12.000€/mois avec Claude Code",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-04-26",
        "url": "https://www.youtube.com/watch?v=iZnp0kQ_NnY",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment faire 12.000€/mois avec Claude Code..."
    },
    {
        "id": "kpG1v9uZd4E",
        "videoId": "kpG1v9uZd4E",
        "title": "Guide Complet Claude Design l Maîtrisez 95% en 20 Minutes",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-04-26",
        "url": "https://www.youtube.com/watch?v=kpG1v9uZd4E",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Guide Complet Claude Design l Maîtrisez 95% en 20 Minutes..."
    },
    {
        "id": "eDhOomO4FpE",
        "videoId": "eDhOomO4FpE",
        "title": "Le paradoxe de l'IA : plus tu progresses, plus tu te perds",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-04-25",
        "url": "https://www.youtube.com/watch?v=eDhOomO4FpE",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le paradoxe de l'IA : plus tu progresses, plus tu te perds..."
    },
    {
        "id": "aWadvdrEP6I",
        "videoId": "aWadvdrEP6I",
        "title": "Claude Code + Blotato : Créer une campagne marketing en 1 prompt",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-04-23",
        "url": "https://www.youtube.com/watch?v=aWadvdrEP6I",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Claude Code + Blotato : Créer une campagne marketing en 1 prompt..."
    },
    {
        "id": "7nAJfe2afoU",
        "videoId": "7nAJfe2afoU",
        "title": "Claude Code + Blotato : 30 Jours de Contenu en 1 Seul Prompt",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-04-23",
        "url": "https://www.youtube.com/watch?v=7nAJfe2afoU",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Claude Code + Blotato : 30 Jours de Contenu en 1 Seul Prompt..."
    },
    {
        "id": "Ac6etyFXc54",
        "videoId": "Ac6etyFXc54",
        "title": "Claude Remplace les Monteurs Vidéos (Tuto Complet)",
        "author": "Baptiste Simard - IA",
        "source": "@BaptIA",
        "date": "2026-04-23",
        "url": "https://www.youtube.com/watch?v=Ac6etyFXc54",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Baptiste Simard - IA : Claude Remplace les Monteurs Vidéos (Tuto Complet)..."
    },
    {
        "id": "lXnCuvAbXrA",
        "videoId": "lXnCuvAbXrA",
        "title": "Agents IA : j'aurai aimé avoir connu ce prompt plus tôt",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-04-22",
        "url": "https://www.youtube.com/watch?v=lXnCuvAbXrA",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : Agents IA : j'aurai aimé avoir connu ce prompt plus tôt..."
    },
    {
        "id": "jyUJUyYEraI",
        "videoId": "jyUJUyYEraI",
        "title": "ChatGPT vient de lancer GPT Image 2.0 (et c’est WOW…)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-04-22",
        "url": "https://www.youtube.com/watch?v=jyUJUyYEraI",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : ChatGPT vient de lancer GPT Image 2.0 (et c’est WOW…)..."
    },
    {
        "id": "dOlYHNSifGc",
        "videoId": "dOlYHNSifGc",
        "title": "7 Exemples DINGUES de ChatGPT Image 2.0 !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-04-22",
        "url": "https://www.youtube.com/watch?v=dOlYHNSifGc",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : 7 Exemples DINGUES de ChatGPT Image 2.0 !..."
    },
    {
        "id": "CkUtbdamfCk",
        "videoId": "CkUtbdamfCk",
        "title": "Je regrette d'avoir créé des interfaces avec l'IA (pas à cause du code)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-04-22",
        "url": "https://www.youtube.com/watch?v=CkUtbdamfCk",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Je regrette d'avoir créé des interfaces avec l'IA (pas à cause du code)..."
    },
    {
        "id": "XByAQxs4yCY",
        "videoId": "XByAQxs4yCY",
        "title": "GPT Image 2 vs Nano Banana 2 : lequel est vraiment le meilleur 🏆",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-04-22",
        "url": "https://www.youtube.com/watch?v=XByAQxs4yCY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : GPT Image 2 vs Nano Banana 2 : lequel est vraiment le meilleur 🏆..."
    },
    {
        "id": "RQhj_I_erVg",
        "videoId": "RQhj_I_erVg",
        "title": "5 secrets sur Claude que personne ne connait !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-04-21",
        "url": "https://www.youtube.com/watch?v=RQhj_I_erVg",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : 5 secrets sur Claude que personne ne connait !..."
    },
    {
        "id": "MduQOd_cDzs",
        "videoId": "MduQOd_cDzs",
        "title": "La plus grosse annonce de l’histoire de Canva (Je ne m’attendais pas à ça !)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-04-20",
        "url": "https://www.youtube.com/watch?v=MduQOd_cDzs",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : La plus grosse annonce de l’histoire de Canva (Je ne m’attendais pas à ça !)..."
    },
    {
        "id": "drl9eIkOHYE",
        "videoId": "drl9eIkOHYE",
        "title": "Faire 10K€/mois dans l'IA sans compétences, c'est facile (c'est mathématique)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-04-19",
        "url": "https://www.youtube.com/watch?v=drl9eIkOHYE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Faire 10K€/mois dans l'IA sans compétences, c'est facile (c'est mathématique)..."
    },
    {
        "id": "H9BNiEn_pJ8",
        "videoId": "H9BNiEn_pJ8",
        "title": "7 Outils IA Indispensables Pour Votre Business",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-04-19",
        "url": "https://www.youtube.com/watch?v=H9BNiEn_pJ8",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : 7 Outils IA Indispensables Pour Votre Business..."
    },
    {
        "id": "kWrWE8q-e9s",
        "videoId": "kWrWE8q-e9s",
        "title": "Claude Design a tué Lovable et Gamma (la preuve en 3 prompts)",
        "author": "Baptiste Simard - IA",
        "source": "@BaptIA",
        "date": "2026-04-19",
        "url": "https://www.youtube.com/watch?v=kWrWE8q-e9s",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Baptiste Simard - IA : Claude Design a tué Lovable et Gamma (la preuve en 3 prompts)..."
    },
    {
        "id": "XphRDltcYSA",
        "videoId": "XphRDltcYSA",
        "title": "Le Second Cerveau IA le plus complet que j'ai vu (démo d'Ulysse Lubin)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-04-18",
        "url": "https://www.youtube.com/watch?v=XphRDltcYSA",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le Second Cerveau IA le plus complet que j'ai vu (démo d'Ulysse Lubin)..."
    },
    {
        "id": "wRaGk8WVBEI",
        "videoId": "wRaGk8WVBEI",
        "title": "Opus 4.7 dans Claude Code : ça CHANGE tout 🔥",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-04-17",
        "url": "https://www.youtube.com/watch?v=wRaGk8WVBEI",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Opus 4.7 dans Claude Code : ça CHANGE tout 🔥..."
    },
    {
        "id": "7sgi0zIf8r0",
        "videoId": "7sgi0zIf8r0",
        "title": "GUIDE COMPLET : Maîtrise Claude OPUS 4.7 en 38 min (débutant) !",
        "author": "Aurélien Fagioli",
        "source": "@AurelienAutomatisation",
        "date": "2026-04-17",
        "url": "https://www.youtube.com/watch?v=7sgi0zIf8r0",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Aurélien Fagioli : GUIDE COMPLET : Maîtrise Claude OPUS 4.7 en 38 min (débutant) !..."
    },
    {
        "id": "R7O2TaM709Y",
        "videoId": "R7O2TaM709Y",
        "title": "J’ai créé une équipe d’Agents IA dans Claude ! (Ils bossent pour moi)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-04-16",
        "url": "https://www.youtube.com/watch?v=R7O2TaM709Y",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : J’ai créé une équipe d’Agents IA dans Claude ! (Ils bossent pour moi)..."
    },
    {
        "id": "2CT3wqam2DY",
        "videoId": "2CT3wqam2DY",
        "title": "Claude OPUS 4.7 vient de sortir !! (J’étais pas prêt)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-04-16",
        "url": "https://www.youtube.com/watch?v=2CT3wqam2DY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Claude OPUS 4.7 vient de sortir !! (J’étais pas prêt)..."
    },
    {
        "id": "kMdJrR3Ku5I",
        "videoId": "kMdJrR3Ku5I",
        "title": "Gemma 4 + Ollama = Claude Code local 🎯(GRATUIT)",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-04-16",
        "url": "https://www.youtube.com/watch?v=kMdJrR3Ku5I",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Gemma 4 + Ollama = Claude Code local 🎯(GRATUIT)..."
    },
    {
        "id": "FkWkC9UEQ-A",
        "videoId": "FkWkC9UEQ-A",
        "title": "J'ai arrêté de payer Claude Code (je te montre comment)",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-04-15",
        "url": "https://www.youtube.com/watch?v=FkWkC9UEQ-A",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : J'ai arrêté de payer Claude Code (je te montre comment)..."
    },
    {
        "id": "1_xVd348jV8",
        "videoId": "1_xVd348jV8",
        "title": "Claude Routines vient de sortir, et c'est DINGUE (Agents 24h/24 et 7j/7)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-04-15",
        "url": "https://www.youtube.com/watch?v=1_xVd348jV8",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Claude Routines vient de sortir, et c'est DINGUE (Agents 24h/24 et 7j/7)..."
    },
    {
        "id": "lZMXl3CfZn8",
        "videoId": "lZMXl3CfZn8",
        "title": "Le second cerveau IA de Karpathy est une impasse (+ ce qu'il devrait faire à la place)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-04-15",
        "url": "https://www.youtube.com/watch?v=lZMXl3CfZn8",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le second cerveau IA de Karpathy est une impasse (+ ce qu'il devrait faire à la place)..."
    },
    {
        "id": "x35M5aKFN78",
        "videoId": "x35M5aKFN78",
        "title": "J'ai testé Claude Managed Agents pour que tu n'aies pas à le faire.",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-04-15",
        "url": "https://www.youtube.com/watch?v=x35M5aKFN78",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : J'ai testé Claude Managed Agents pour que tu n'aies pas à le faire...."
    },
    {
        "id": "9RVzj8bJj6g",
        "videoId": "9RVzj8bJj6g",
        "title": "Copilot Cowork est désormais disponible... quelle folie !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-04-14",
        "url": "https://www.youtube.com/watch?v=9RVzj8bJj6g",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Copilot Cowork est désormais disponible... quelle folie !..."
    },
    {
        "id": "9_T-RzbA_EQ",
        "videoId": "9_T-RzbA_EQ",
        "title": "Actus IA : une IA a embauché des Humains (ça fait peur)",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-04-14",
        "url": "https://www.youtube.com/watch?v=9_T-RzbA_EQ",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Actus IA : une IA a embauché des Humains (ça fait peur)..."
    },
    {
        "id": "Dv6suL5-fAE",
        "videoId": "Dv6suL5-fAE",
        "title": "7 leviers (que personne n’utilise) pour boire la concurrence dans l’IA.",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-04-13",
        "url": "https://www.youtube.com/watch?v=Dv6suL5-fAE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : 7 leviers (que personne n’utilise) pour boire la concurrence dans l’IA...."
    },
    {
        "id": "LbPvgHNthJs",
        "videoId": "LbPvgHNthJs",
        "title": "J'ai appris l'espagnol en 2 semaines avec l'IA (Je teste ça à Séville)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-04-13",
        "url": "https://www.youtube.com/watch?v=LbPvgHNthJs",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : J'ai appris l'espagnol en 2 semaines avec l'IA (Je teste ça à Séville)..."
    },
    {
        "id": "VeG1rqTZ-EM",
        "videoId": "VeG1rqTZ-EM",
        "title": "OpenClaw, Claude Code, PaperClip... mais toujours 0€ de CA (voici pourquoi).",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-04-12",
        "url": "https://www.youtube.com/watch?v=VeG1rqTZ-EM",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : OpenClaw, Claude Code, PaperClip... mais toujours 0€ de CA (voici pourquoi)...."
    },
    {
        "id": "kEedBb-kT9g",
        "videoId": "kEedBb-kT9g",
        "title": "Comment maîtriser Claude Cowork mieux que 99% de la population",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-04-12",
        "url": "https://www.youtube.com/watch?v=kEedBb-kT9g",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comment maîtriser Claude Cowork mieux que 99% de la population..."
    },
    {
        "id": "w7Hli9du028",
        "videoId": "w7Hli9du028",
        "title": "Ne payez plus pour n8n : La technique pour tout avoir en illimité (Tuto VPS)",
        "author": "Ousmane Automatise",
        "source": "@ousmanedf",
        "date": "2026-04-11",
        "url": "https://www.youtube.com/watch?v=w7Hli9du028",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ousmane Automatise : Ne payez plus pour n8n : La technique pour tout avoir en illimité (Tuto VPS)..."
    },
    {
        "id": "uIjp0Bx9mWg",
        "videoId": "uIjp0Bx9mWg",
        "title": "Où vont vraiment vos données quand vous parlez à l'IA",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-04-11",
        "url": "https://www.youtube.com/watch?v=uIjp0Bx9mWg",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Où vont vraiment vos données quand vous parlez à l'IA..."
    },
    {
        "id": "I5FbWuX7AZQ",
        "videoId": "I5FbWuX7AZQ",
        "title": "Openclaw 4.9 va te CHANGER la VIE - Voici pourquoi",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-04-10",
        "url": "https://www.youtube.com/watch?v=I5FbWuX7AZQ",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : Openclaw 4.9 va te CHANGER la VIE - Voici pourquoi..."
    },
    {
        "id": "_vUbdaThfag",
        "videoId": "_vUbdaThfag",
        "title": "Microsoft Copilot a totalement changé ! (7 exemples INCROYABLES)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-04-09",
        "url": "https://www.youtube.com/watch?v=_vUbdaThfag",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Microsoft Copilot a totalement changé ! (7 exemples INCROYABLES)..."
    },
    {
        "id": "fGnr9h5JUGc",
        "videoId": "fGnr9h5JUGc",
        "title": "Paperclip + OpenClaw : mon équipe IA tourne 24h/24",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-04-09",
        "url": "https://www.youtube.com/watch?v=fGnr9h5JUGc",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Paperclip + OpenClaw : mon équipe IA tourne 24h/24..."
    },
    {
        "id": "e97xFyORj_k",
        "videoId": "e97xFyORj_k",
        "title": "Google vient de tout changer (Agent Vocal GEMINI 3.1 FLASH LIVE) !",
        "author": "Aurélien Fagioli",
        "source": "@AurelienAutomatisation",
        "date": "2026-04-09",
        "url": "https://www.youtube.com/watch?v=e97xFyORj_k",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Aurélien Fagioli : Google vient de tout changer (Agent Vocal GEMINI 3.1 FLASH LIVE) !..."
    },
    {
        "id": "ha6JkWePF94",
        "videoId": "ha6JkWePF94",
        "title": "J'AI LAISSÉ UNE IA CHOISIR MON APPARTEMENT ! (Résultat CHOQUANT)",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-04-08",
        "url": "https://www.youtube.com/watch?v=ha6JkWePF94",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : J'AI LAISSÉ UNE IA CHOISIR MON APPARTEMENT ! (Résultat CHOQUANT)..."
    },
    {
        "id": "iLpyTd5biIA",
        "videoId": "iLpyTd5biIA",
        "title": "La nouvelle IA de Claude vient de changer Internet pour toujours",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-04-08",
        "url": "https://www.youtube.com/watch?v=iLpyTd5biIA",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : La nouvelle IA de Claude vient de changer Internet pour toujours..."
    },
    {
        "id": "ep5BYfZtINM",
        "videoId": "ep5BYfZtINM",
        "title": "Utilise ce mode pour maîtriser Claude Code 🧑‍💻",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-04-08",
        "url": "https://www.youtube.com/watch?v=ep5BYfZtINM",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Utilise ce mode pour maîtriser Claude Code 🧑‍💻..."
    },
    {
        "id": "svRtxQemC9I",
        "videoId": "svRtxQemC9I",
        "title": "J'ai Testé Ultra Plan vs Plan Normal sur Claude Code (Résultat Dingue)",
        "author": "Baptiste Simard - IA",
        "source": "@BaptIA",
        "date": "2026-04-08",
        "url": "https://www.youtube.com/watch?v=svRtxQemC9I",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Baptiste Simard - IA : J'ai Testé Ultra Plan vs Plan Normal sur Claude Code (Résultat Dingue)..."
    },
    {
        "id": "dFM7dnRRdM8",
        "videoId": "dFM7dnRRdM8",
        "title": "Le nouveau GPT Image 2 dans ChatGPT est époustouflant !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-04-07",
        "url": "https://www.youtube.com/watch?v=dFM7dnRRdM8",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Le nouveau GPT Image 2 dans ChatGPT est époustouflant !..."
    },
    {
        "id": "qn-mTwCVO88",
        "videoId": "qn-mTwCVO88",
        "title": "Si tu débutes sur Claude Code apprends ça 👀",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-04-07",
        "url": "https://www.youtube.com/watch?v=qn-mTwCVO88",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Si tu débutes sur Claude Code apprends ça 👀..."
    },
    {
        "id": "6d9HeBlu7Iw",
        "videoId": "6d9HeBlu7Iw",
        "title": "Si je débutais Claude Code aujourd'hui, voici ce que j'apprendrais.",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-04-07",
        "url": "https://www.youtube.com/watch?v=6d9HeBlu7Iw",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Si je débutais Claude Code aujourd'hui, voici ce que j'apprendrais...."
    },
    {
        "id": "BWwGSK-pKpY",
        "videoId": "BWwGSK-pKpY",
        "title": "Comment apprendre n'importe quelle langue avec l'IA ? (En partant de ZERO)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-04-06",
        "url": "https://www.youtube.com/watch?v=BWwGSK-pKpY",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Comment apprendre n'importe quelle langue avec l'IA ? (En partant de ZERO)..."
    },
    {
        "id": "-xOk8SVdC6U",
        "videoId": "-xOk8SVdC6U",
        "title": "1,8 Milliards de dollars TOUT SEUL grâce à l'IA (Comment il a fait ?)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-04-05",
        "url": "https://www.youtube.com/watch?v=-xOk8SVdC6U",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : 1,8 Milliards de dollars TOUT SEUL grâce à l'IA (Comment il a fait ?)..."
    },
    {
        "id": "m2QptFP0sLM",
        "videoId": "m2QptFP0sLM",
        "title": "Comment Créer des Sites Web INCROYABLE avec Claude IA",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-04-05",
        "url": "https://www.youtube.com/watch?v=m2QptFP0sLM",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comment Créer des Sites Web INCROYABLE avec Claude IA..."
    },
    {
        "id": "ecL5Kt4v-kI",
        "videoId": "ecL5Kt4v-kI",
        "title": "La fonctionnalité cachée de Claude en 3 clics 🤫  #astuce",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-04-05",
        "url": "https://www.youtube.com/watch?v=ecL5Kt4v-kI",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : La fonctionnalité cachée de Claude en 3 clics 🤫  #astuce..."
    },
    {
        "id": "95YMCtc9SZk",
        "videoId": "95YMCtc9SZk",
        "title": "Automatisez votre quotidien avec Claude grâce à cette vidéo !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-04-02",
        "url": "https://www.youtube.com/watch?v=95YMCtc9SZk",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Automatisez votre quotidien avec Claude grâce à cette vidéo !..."
    },
    {
        "id": "RKKK4uJ1ygU",
        "videoId": "RKKK4uJ1ygU",
        "title": "Maitriser TOUT NotebookLM en 26 minutes (Tuto Complet)",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-04-02",
        "url": "https://www.youtube.com/watch?v=RKKK4uJ1ygU",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Maitriser TOUT NotebookLM en 26 minutes (Tuto Complet)..."
    },
    {
        "id": "FpVB_B6etu4",
        "videoId": "FpVB_B6etu4",
        "title": "GUIDE GRATUIT : Maîtriser Antigravity comme un PRO (1h30)",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-04-01",
        "url": "https://www.youtube.com/watch?v=FpVB_B6etu4",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : GUIDE GRATUIT : Maîtriser Antigravity comme un PRO (1h30)..."
    },
    {
        "id": "mUFTkEVVeK8",
        "videoId": "mUFTkEVVeK8",
        "title": "Codex arrive dans Claude Code (TEST)",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-04-01",
        "url": "https://www.youtube.com/watch?v=mUFTkEVVeK8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Codex arrive dans Claude Code (TEST)..."
    },
    {
        "id": "PiMNs7xHp2M",
        "videoId": "PiMNs7xHp2M",
        "title": "CLAUDE CODE Automatise 100% de Ton PC : Il Fait TOUT à Ta Place ! (même débutant)",
        "author": "Aurélien Fagioli",
        "source": "@AurelienAutomatisation",
        "date": "2026-04-01",
        "url": "https://www.youtube.com/watch?v=PiMNs7xHp2M",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Aurélien Fagioli : CLAUDE CODE Automatise 100% de Ton PC : Il Fait TOUT à Ta Place ! (même débutant)..."
    }
];
