// Fichier généré automatiquement le 2026-08-23T06:33:07.430Z
// Ne pas modifier manuellement

export const lastUpdate = "6:33:07 AM 8/23/2026";

export const sources = [
    {
        "handle": "@EtienneTillierStudio",
        "name": "Etienne Tillier",
        "id": "UCUlm3shqkgVNHLomYWZsfYA",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@Simon_bcome",
        "name": "Simon Music",
        "id": "UCaryUIRfj7KAikH_ogrOzig",
        "theme": "Business & Monétisation IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@HenriExplorIA",
        "name": "Henri · ExplorIA",
        "id": "UCxx03UqvjTy9w8iomLwTSuQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@elliottpierret",
        "name": "Elliott Pierret",
        "id": "UCnJAGhDDEPdvY2g4ipf9PMQ",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@RenaudDekode",
        "name": "Renaud Dékode",
        "id": "UCOWu-2h4IpoEjhsRlTuesFg",
        "theme": "Actualités Tech",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@ousmanedf",
        "name": "Ousmane Automatise",
        "id": "UC1o5Eo5Qf12_f6D836PsoPw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@yassine-sdiri",
        "name": "Yassine Sdiri",
        "id": "UC94UeaPuTt_L51RkDxj9d_w",
        "theme": "Business & Monétisation IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@cedric_effi10",
        "name": "Cédric Girard",
        "id": "UCjhLy8XRh4Q0NM2CD6pFPYQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@EliottMeunier",
        "name": "Eliott Meunier",
        "id": "UCPo1nFSGNkyzrA9yvtkEvIw",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@reverdybusiness",
        "name": "Lucas Reverdy",
        "id": "UCabbBG5KYGtdTibrl_XHLOw",
        "theme": "Business & Monétisation IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@JulienSnsn",
        "name": "Julien Sanson",
        "id": "UCK85rF_WKv1N6ojTzVbj3yw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@NerdyKings",
        "name": "Nerdy Kings",
        "id": "UCp7vimq7dYKiVAJLPyI0GcA",
        "theme": "Outils & Modèles IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@iAlan_automatise",
        "name": "iAlan",
        "id": "UCdROsT8FZ2pacpipymmmaPw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@LouisGraffeuil",
        "name": "Louis Graffeuil",
        "id": "UChkCdoCUCNYizE8d9TXsi4A",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@Hugo_Buisson",
        "name": "Hugo Buisson",
        "id": "UCeZvp_y5meYlfcGCFhl6UJQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@audelalia",
        "name": "Au-delà l'IA",
        "id": "UCNSPV84q4QlUtle6MS_7v1Q",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@thomasbssh",
        "name": "Thomas Berton",
        "id": "UCxOWUTmenPJj5V6_g2-CS1g",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@JonasEkanbo",
        "name": "Jonas Ekanbo",
        "id": "UCF2fb5WylqKbw0SgOlJKXMA",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@LudovicSalenne",
        "name": "Ludo Salenne",
        "id": "UCnnYqSNKKygemgmxC9PyLTw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@AurelienAutomatisation",
        "name": "Aurélien Fagioli",
        "id": "UCdL89Z0gQUDc1HT1882AGLw",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@BaptIA",
        "name": "Baptiste Simard - IA",
        "id": "UCzabGLybo9x307MkDtqTyFQ",
        "theme": "Agents & Automatisation",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        "handle": "@LudovicNedelec",
        "name": "Ludovic Nédélec",
        "id": "UCMJ00y5KeFDKzYh9D6Lc41A",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://yt3.googleusercontent.com/ytc/AIdro_nL7W9X9Tj9s_c_fG_pQ_m_M_M0=s176-c-k-c0x00ffffff-no-rj"
    }
];

export const themes = [
    "Tous",
    "Agents & Automatisation",
    "Vibe Coding & Dev IA",
    "Outils & Modèles IA",
    "Business & Monétisation IA",
    "Productivité & Second Cerveau",
    "Actualités Tech"
];

export const allVideos = [
    {
        "id": "A9eNMubDEm4",
        "videoId": "A9eNMubDEm4",
        "title": "5 prompts parfaits pour éviter que ton app se fasse hacker !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-22",
        "url": "https://www.youtube.com/watch?v=A9eNMubDEm4",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 5 prompts parfaits pour éviter que ton app se fasse hacker !..."
    },
    {
        "id": "2Lq75AyVjdE",
        "videoId": "2Lq75AyVjdE",
        "title": "Transforme une video en site web anime",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-22",
        "url": "https://www.youtube.com/watch?v=2Lq75AyVjdE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Transforme une video en site web anime..."
    },
    {
        "id": "NFcOVuoqnIs",
        "videoId": "NFcOVuoqnIs",
        "title": "Cet outil est completement dingue.  Cobalt : tu colles n'importe quel lien (Instagram, TikTok, YouTu",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-22",
        "url": "https://www.youtube.com/watch?v=NFcOVuoqnIs",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Cet outil est completement dingue.  Cobalt : tu colles n'importe quel lien (Instagram, TikTok, YouTu..."
    },
    {
        "id": "vy8keMoC_5c",
        "videoId": "vy8keMoC_5c",
        "title": "5 signes que tu sais vraiment utiliser l'IA !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-21",
        "url": "https://www.youtube.com/watch?v=vy8keMoC_5c",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 5 signes que tu sais vraiment utiliser l'IA !..."
    },
    {
        "id": "2aHVkfXcpJA",
        "videoId": "2aHVkfXcpJA",
        "title": "Le seul dépôt Claude que tu as besoin !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-21",
        "url": "https://www.youtube.com/watch?v=2aHVkfXcpJA",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Le seul dépôt Claude que tu as besoin !..."
    },
    {
        "id": "Od6j6r21FdE",
        "videoId": "Od6j6r21FdE",
        "title": "3 astuces pour des visuels IA de pro",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-21",
        "url": "https://www.youtube.com/watch?v=Od6j6r21FdE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : 3 astuces pour des visuels IA de pro..."
    },
    {
        "id": "o_k063WsJhE",
        "videoId": "o_k063WsJhE",
        "title": "5 plugins pour créer des sites web incroyables avec Claude !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=o_k063WsJhE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 5 plugins pour créer des sites web incroyables avec Claude !..."
    },
    {
        "id": "0IjPwfgGB0M",
        "videoId": "0IjPwfgGB0M",
        "title": "7 utilisations INCROYABLES de ChatGPT WORK (il travaille à ta place)",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=0IjPwfgGB0M",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 7 utilisations INCROYABLES de ChatGPT WORK (il travaille à ta place)..."
    },
    {
        "id": "QzK6E8C0TT8",
        "videoId": "QzK6E8C0TT8",
        "title": "8 outils pour construire un business avec Claude !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=QzK6E8C0TT8",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 8 outils pour construire un business avec Claude !..."
    },
    {
        "id": "uF3C3zQxZ-o",
        "videoId": "uF3C3zQxZ-o",
        "title": "C’est décidé, j'arrête Claude Code pour Codex !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=uF3C3zQxZ-o",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : C’est décidé, j'arrête Claude Code pour Codex !..."
    },
    {
        "id": "lNpseFbzM5Y",
        "videoId": "lNpseFbzM5Y",
        "title": "Deepseek Harness : La fin de Claude code ? 🤯",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=lNpseFbzM5Y",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Deepseek Harness : La fin de Claude code ? 🤯..."
    },
    {
        "id": "_EAfv6hGLcs",
        "videoId": "_EAfv6hGLcs",
        "title": "J'ai Automatisé 100% de mes Posts avec ce Script [GitHub]",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=_EAfv6hGLcs",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : J'ai Automatisé 100% de mes Posts avec ce Script [GitHub]..."
    },
    {
        "id": "Kmlebm-Otp8",
        "videoId": "Kmlebm-Otp8",
        "title": "Cette TECHNIQUE + CLAUDE CODE = un site à 12'300€ (en 20 min)",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=Kmlebm-Otp8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Cette TECHNIQUE + CLAUDE CODE = un site à 12'300€ (en 20 min)..."
    },
    {
        "id": "Y-C_71H-mAg",
        "videoId": "Y-C_71H-mAg",
        "title": "Anthropic vient de lancer un avertissement pour les 6 à 12 prochains mois...",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=Y-C_71H-mAg",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Anthropic vient de lancer un avertissement pour les 6 à 12 prochains mois......"
    },
    {
        "id": "3lT8i7qdshI",
        "videoId": "3lT8i7qdshI",
        "title": "Claude marque tout son contenu avec des filigranes !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=3lT8i7qdshI",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Claude marque tout son contenu avec des filigranes !..."
    },
    {
        "id": "VCntIHygMlg",
        "videoId": "VCntIHygMlg",
        "title": "DeepSeek lâche une bombe : DeepSeek Harness (actu IA)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=VCntIHygMlg",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : DeepSeek lâche une bombe : DeepSeek Harness (actu IA)..."
    },
    {
        "id": "OExbLboNEaw",
        "videoId": "OExbLboNEaw",
        "title": "DeepSeek Harness : La Fin de Claude Code ? (Installation + Test)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=OExbLboNEaw",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : DeepSeek Harness : La Fin de Claude Code ? (Installation + Test)..."
    },
    {
        "id": "GwVB8H69_jE",
        "videoId": "GwVB8H69_jE",
        "title": "Un mec a open sourcé toutes les données de Wall Street",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=GwVB8H69_jE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Un mec a open sourcé toutes les données de Wall Street..."
    },
    {
        "id": "_RmZ9iE36jM",
        "videoId": "_RmZ9iE36jM",
        "title": "Ton plan Claude à 20 dollars peut durer comme le plan à 100 !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=_RmZ9iE36jM",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Ton plan Claude à 20 dollars peut durer comme le plan à 100 !..."
    },
    {
        "id": "E_vNH-XoXbQ",
        "videoId": "E_vNH-XoXbQ",
        "title": "Les hacks ultimes pour économiser vos tokens dans Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=E_vNH-XoXbQ",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Les hacks ultimes pour économiser vos tokens dans Claude !..."
    },
    {
        "id": "89J8aJpzBLc",
        "videoId": "89J8aJpzBLc",
        "title": "Prédire les cyclones avec l’IA #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=89J8aJpzBLc",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Prédire les cyclones avec l’IA #actu..."
    },
    {
        "id": "7PEBbSp9kws",
        "videoId": "7PEBbSp9kws",
        "title": "Muse Glimmer : le retour inattendu de Meta dans l’open source",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=7PEBbSp9kws",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Muse Glimmer : le retour inattendu de Meta dans l’open source..."
    },
    {
        "id": "4AjMSaNAI1w",
        "videoId": "4AjMSaNAI1w",
        "title": "Claude fait une découverte folle après 650 échecs",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=4AjMSaNAI1w",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Claude fait une découverte folle après 650 échecs..."
    },
    {
        "id": "riqjZ7H23Ys",
        "videoId": "riqjZ7H23Ys",
        "title": "Le robot qui fait ta valise #xiaomi",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=riqjZ7H23Ys",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le robot qui fait ta valise #xiaomi..."
    },
    {
        "id": "aQ5Sa4OoOjA",
        "videoId": "aQ5Sa4OoOjA",
        "title": "650 échecs plus tard, Claude fait une découverte",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=aQ5Sa4OoOjA",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : 650 échecs plus tard, Claude fait une découverte..."
    },
    {
        "id": "a-bxMZnM-n0",
        "videoId": "a-bxMZnM-n0",
        "title": "Transforme n'importe quel livre en skill Claude Code",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=a-bxMZnM-n0",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Transforme n'importe quel livre en skill Claude Code..."
    },
    {
        "id": "tb-7zB5pwng",
        "videoId": "tb-7zB5pwng",
        "title": "Ces 10 astuces Claude remplacent vos apps payantes",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=tb-7zB5pwng",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Ces 10 astuces Claude remplacent vos apps payantes..."
    },
    {
        "id": "QbcPDv-s2-E",
        "videoId": "QbcPDv-s2-E",
        "title": "Comment Bâtir un Business en SOLO avec l’IA (grâce à Claude Code)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=QbcPDv-s2-E",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment Bâtir un Business en SOLO avec l’IA (grâce à Claude Code)..."
    },
    {
        "id": "ZNEPOzbxmEY",
        "videoId": "ZNEPOzbxmEY",
        "title": "Qu'est-ce qui se passe quand tu demandes à ChatGPT ce qu'il sait secrètement sur toi ?",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=ZNEPOzbxmEY",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Qu'est-ce qui se passe quand tu demandes à ChatGPT ce qu'il sait secrètement sur toi ?..."
    },
    {
        "id": "aBGsqXv3nVc",
        "videoId": "aBGsqXv3nVc",
        "title": "Cet outil te permet de coder sans limite !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=aBGsqXv3nVc",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Cet outil te permet de coder sans limite !..."
    },
    {
        "id": "6GuY15wy6DY",
        "videoId": "6GuY15wy6DY",
        "title": "Le problème de Claude Code",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=6GuY15wy6DY",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le problème de Claude Code..."
    },
    {
        "id": "4rFx2B6UgiA",
        "videoId": "4rFx2B6UgiA",
        "title": "Ce repo open source découpe tes vidéos en shorts tout seul",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=4rFx2B6UgiA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Ce repo open source découpe tes vidéos en shorts tout seul..."
    },
    {
        "id": "qamzMkCO8Sg",
        "videoId": "qamzMkCO8Sg",
        "title": "20 choses à dire à Claude d'ajouter à ton site avant de le lancer !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-15",
        "url": "https://www.youtube.com/watch?v=qamzMkCO8Sg",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 20 choses à dire à Claude d'ajouter à ton site avant de le lancer !..."
    },
    {
        "id": "dDMxmwIGYoQ",
        "videoId": "dDMxmwIGYoQ",
        "title": "Le World Mental Modeling",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-15",
        "url": "https://www.youtube.com/watch?v=dDMxmwIGYoQ",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le World Mental Modeling..."
    },
    {
        "id": "FkiAl-IOLyo",
        "videoId": "FkiAl-IOLyo",
        "title": "Quelqu'un vient de transformer le langage design d'Apple en un skill Claude !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=FkiAl-IOLyo",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Quelqu'un vient de transformer le langage design d'Apple en un skill Claude !..."
    },
    {
        "id": "EGL2DQ1MJds",
        "videoId": "EGL2DQ1MJds",
        "title": "La nouvelle fonctionnalité incroyable de Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=EGL2DQ1MJds",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : La nouvelle fonctionnalité incroyable de Claude !..."
    },
    {
        "id": "Q2Aeg6AErAM",
        "videoId": "Q2Aeg6AErAM",
        "title": "Alibaba s’ouvre enfin !",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=Q2Aeg6AErAM",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Alibaba s’ouvre enfin !..."
    },
    {
        "id": "wyI8RKwI8po",
        "videoId": "wyI8RKwI8po",
        "title": "Récupère tous les leads d'Internet en langage naturel",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=wyI8RKwI8po",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Récupère tous les leads d'Internet en langage naturel..."
    },
    {
        "id": "eRaek8u2CS8",
        "videoId": "eRaek8u2CS8",
        "title": "Commente Vocal pour avoir le prompt !",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=eRaek8u2CS8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Commente Vocal pour avoir le prompt !..."
    },
    {
        "id": "odK-rqGSYR8",
        "videoId": "odK-rqGSYR8",
        "title": "Demandez à l'IA de poser des questions avant TOUT ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=odK-rqGSYR8",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Demandez à l'IA de poser des questions avant TOUT ! #shorts...",
        "isShort": true
    },
    {
        "id": "5em87yYtJUM",
        "videoId": "5em87yYtJUM",
        "title": "Voici comment configurer Claude en une journée !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-13",
        "url": "https://www.youtube.com/watch?v=5em87yYtJUM",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Voici comment configurer Claude en une journée !..."
    },
    {
        "id": "gK1mBVZUlVQ",
        "videoId": "gK1mBVZUlVQ",
        "title": "Claude + DataForSEO : Le SEO Ne Sera Plus Jamais Pareil",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-13",
        "url": "https://www.youtube.com/watch?v=gK1mBVZUlVQ",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Claude + DataForSEO : Le SEO Ne Sera Plus Jamais Pareil..."
    },
    {
        "id": "XgnYGTaPLws",
        "videoId": "XgnYGTaPLws",
        "title": "Longcat 2.0 : La fin des GPU NVIDIA ? 🇨🇳",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-13",
        "url": "https://www.youtube.com/watch?v=XgnYGTaPLws",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Longcat 2.0 : La fin des GPU NVIDIA ? 🇨🇳..."
    },
    {
        "id": "P-nOn0R2hdI",
        "videoId": "P-nOn0R2hdI",
        "title": "Je te fais gagner 72 h de Seedance 2.5",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-13",
        "url": "https://www.youtube.com/watch?v=P-nOn0R2hdI",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Je te fais gagner 72 h de Seedance 2.5..."
    },
    {
        "id": "kHcqcR0lQz0",
        "videoId": "kHcqcR0lQz0",
        "title": "Sora : La Révolution Vidéo IA Qui Va Tout Changer ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-13",
        "url": "https://www.youtube.com/watch?v=kHcqcR0lQz0",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Sora : La Révolution Vidéo IA Qui Va Tout Changer ! #shorts...",
        "isShort": true
    },
    {
        "id": "-0IY4UpI2JM",
        "videoId": "-0IY4UpI2JM",
        "title": "Claude peut planifier toute ta semaine en 5 minutes !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=-0IY4UpI2JM",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Claude peut planifier toute ta semaine en 5 minutes !..."
    },
    {
        "id": "ocISgzNw6HY",
        "videoId": "ocISgzNw6HY",
        "title": "Claude vient de tuer le looks maxxing !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=ocISgzNw6HY",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Claude vient de tuer le looks maxxing !..."
    },
    {
        "id": "CQGNFHJ8xS8",
        "videoId": "CQGNFHJ8xS8",
        "title": "Ce retournement d’Alibaba en dit long sur l’IA (actu IA)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=CQGNFHJ8xS8",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Ce retournement d’Alibaba en dit long sur l’IA (actu IA)..."
    },
    {
        "id": "7ieeYRie5po",
        "videoId": "7ieeYRie5po",
        "title": "La sortie de Seedance 2.5 #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=7ieeYRie5po",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : La sortie de Seedance 2.5 #actu..."
    },
    {
        "id": "nmsk1rYHNYc",
        "videoId": "nmsk1rYHNYc",
        "title": "La Chine vient de prouver quelque chose d’énorme (LongCat 2.0)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=nmsk1rYHNYc",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : La Chine vient de prouver quelque chose d’énorme (LongCat 2.0)..."
    },
    {
        "id": "BRmdqp9QIto",
        "videoId": "BRmdqp9QIto",
        "title": "Seedance 2.5 : Miracle ou Arnaque ? (crash test)",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=BRmdqp9QIto",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Seedance 2.5 : Miracle ou Arnaque ? (crash test)..."
    },
    {
        "id": "CxDNjAIHSJc",
        "videoId": "CxDNjAIHSJc",
        "title": "Cloud Code: Prenez le contrôle TOTAL de votre ordinateur ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=CxDNjAIHSJc",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Cloud Code: Prenez le contrôle TOTAL de votre ordinateur ! #shorts...",
        "isShort": true
    },
    {
        "id": "U-8CR0yIKy0",
        "videoId": "U-8CR0yIKy0",
        "title": "IA hors de contrôle: L'IA inscrite à un webinaire de 3900€ ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=U-8CR0yIKy0",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : IA hors de contrôle: L'IA inscrite à un webinaire de 3900€ ! #shorts...",
        "isShort": true
    },
    {
        "id": "lmU9IBKEUno",
        "videoId": "lmU9IBKEUno",
        "title": "Arrêtez d'utiliser Copilot sans connaître ces 7 astuces !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=lmU9IBKEUno",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Arrêtez d'utiliser Copilot sans connaître ces 7 astuces !..."
    },
    {
        "id": "FK689G6PZsI",
        "videoId": "FK689G6PZsI",
        "title": "L’IA vidéo de Netflix #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=FK689G6PZsI",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : L’IA vidéo de Netflix #actu..."
    },
    {
        "id": "2pdYzn4BmM4",
        "videoId": "2pdYzn4BmM4",
        "title": "Ta voix en local, gratuite et open source",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=2pdYzn4BmM4",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Ta voix en local, gratuite et open source..."
    },
    {
        "id": "LWvjJkLtDhQ",
        "videoId": "LWvjJkLtDhQ",
        "title": "AIOS: L'IA sécurisée, votre environnement isolé et protégé! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=LWvjJkLtDhQ",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : AIOS: L'IA sécurisée, votre environnement isolé et protégé! #shorts...",
        "isShort": true
    },
    {
        "id": "fVtO2xdsvXU",
        "videoId": "fVtO2xdsvXU",
        "title": "Claude Code : Outils payants ? C'est terminé, c'est gratuit ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=fVtO2xdsvXU",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Claude Code : Outils payants ? C'est terminé, c'est gratuit ! #shorts...",
        "isShort": true
    },
    {
        "id": "tHEWNkr87eo",
        "videoId": "tHEWNkr87eo",
        "title": "Générer une vidéo avec du son stéréo natif #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=tHEWNkr87eo",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Générer une vidéo avec du son stéréo natif #actu..."
    },
    {
        "id": "H9tBaUmQLCc",
        "videoId": "H9tBaUmQLCc",
        "title": "Gemma 4 change la vision des IA",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=H9tBaUmQLCc",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Gemma 4 change la vision des IA..."
    },
    {
        "id": "lQX95S48FX0",
        "videoId": "lQX95S48FX0",
        "title": "Tes posts partent tout seuls",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=lQX95S48FX0",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Tes posts partent tout seuls..."
    },
    {
        "id": "u_t27awaU5U",
        "videoId": "u_t27awaU5U",
        "title": "L'IA qui pense pour vous: Routines et Actions Autonomes ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=u_t27awaU5U",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : L'IA qui pense pour vous: Routines et Actions Autonomes ! #shorts...",
        "isShort": true
    },
    {
        "id": "f5-LE9BkjC0",
        "videoId": "f5-LE9BkjC0",
        "title": "Perplexity: Testez TOUTES les IA avec UN SEUL abonnement ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=f5-LE9BkjC0",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Perplexity: Testez TOUTES les IA avec UN SEUL abonnement ! #shorts...",
        "isShort": true
    },
    {
        "id": "EQt4H1aDWBw",
        "videoId": "EQt4H1aDWBw",
        "title": "Des employés IA gratuits pour tous (merci le cofondateur de Twitter)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=EQt4H1aDWBw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Des employés IA gratuits pour tous (merci le cofondateur de Twitter)..."
    },
    {
        "id": "WFWNKIohrEc",
        "videoId": "WFWNKIohrEc",
        "title": "Dans les coulisses de mon Agence IA",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=WFWNKIohrEc",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Dans les coulisses de mon Agence IA..."
    },
    {
        "id": "4km3oLGe-iQ",
        "videoId": "4km3oLGe-iQ",
        "title": "Personne ne réalise ce que le nouveau ChatGPT peut faire",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=4km3oLGe-iQ",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Personne ne réalise ce que le nouveau ChatGPT peut faire..."
    },
    {
        "id": "ni8BUQYm_QA",
        "videoId": "ni8BUQYm_QA",
        "title": "Nouveau modèle DeepSeek V4 Flash #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=ni8BUQYm_QA",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Nouveau modèle DeepSeek V4 Flash #actu..."
    },
    {
        "id": "eQ2TpNKmdqw",
        "videoId": "eQ2TpNKmdqw",
        "title": "Gemma 4 change complètement la vision des IA",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=eQ2TpNKmdqw",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Gemma 4 change complètement la vision des IA..."
    },
    {
        "id": "39jsTqXYWCY",
        "videoId": "39jsTqXYWCY",
        "title": "Open source chinois ou modele ferme ?",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=39jsTqXYWCY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Open source chinois ou modele ferme ?..."
    },
    {
        "id": "nvQ6L7q3sWs",
        "videoId": "nvQ6L7q3sWs",
        "title": "Transformez vos prompts ratés en succès avec le Meta Aspect ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=nvQ6L7q3sWs",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Transformez vos prompts ratés en succès avec le Meta Aspect ! #shorts...",
        "isShort": true
    },
    {
        "id": "nhGbYbWbzdQ",
        "videoId": "nhGbYbWbzdQ",
        "title": "86 jours: La révolution NanoBanana Pro a tout changé ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=nhGbYbWbzdQ",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : 86 jours: La révolution NanoBanana Pro a tout changé ! #shorts...",
        "isShort": true
    },
    {
        "id": "-TVOe0WqSro",
        "videoId": "-TVOe0WqSro",
        "title": "Comment créer un site web avec ChatGPT et Hostinger Horizon",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=-TVOe0WqSro",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Comment créer un site web avec ChatGPT et Hostinger Horizon..."
    },
    {
        "id": "eO82me1syHk",
        "videoId": "eO82me1syHk",
        "title": "Le style Apple pour tes sites, en un skill",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-08",
        "url": "https://www.youtube.com/watch?v=eO82me1syHk",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Le style Apple pour tes sites, en un skill..."
    },
    {
        "id": "vQgvWWwMvl8",
        "videoId": "vQgvWWwMvl8",
        "title": "Test Claude IA : Préparation Réunion Automatisée en 1 Minute ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-08",
        "url": "https://www.youtube.com/watch?v=vQgvWWwMvl8",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : Test Claude IA : Préparation Réunion Automatisée en 1 Minute ! #shorts...",
        "isShort": true
    },
    {
        "id": "RTeZrp-nPbw",
        "videoId": "RTeZrp-nPbw",
        "title": "ChatGPT: Le succès fou de l'IA que même Elon Musk trouve fascinant ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-08",
        "url": "https://www.youtube.com/watch?v=RTeZrp-nPbw",
        "category": "Vidéos Promotionnelles",
        "summary": "Nouveauté de Thomas Berton : ChatGPT: Le succès fou de l'IA que même Elon Musk trouve fascinant ! #shorts...",
        "isShort": true
    },
    {
        "id": "UYe70-lHLII",
        "videoId": "UYe70-lHLII",
        "title": "J'ai laissé Claude monter cette vidéo (et je te montre TOUT)",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-07",
        "url": "https://www.youtube.com/watch?v=UYe70-lHLII",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : J'ai laissé Claude monter cette vidéo (et je te montre TOUT)..."
    },
    {
        "id": "Sx7PxWz8p4g",
        "videoId": "Sx7PxWz8p4g",
        "title": "Mage-Flow : Générer des images en Open Source #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-06",
        "url": "https://www.youtube.com/watch?v=Sx7PxWz8p4g",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Mage-Flow : Générer des images en Open Source #actu..."
    },
    {
        "id": "WBJcNbwLSpI",
        "videoId": "WBJcNbwLSpI",
        "title": "Deepseek devient 7x plus puissant !",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-06",
        "url": "https://www.youtube.com/watch?v=WBJcNbwLSpI",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Deepseek devient 7x plus puissant !..."
    },
    {
        "id": "xAlXes0E34k",
        "videoId": "xAlXes0E34k",
        "title": "Claude Design vient de sortir le Motion Design par IA",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=xAlXes0E34k",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Claude Design vient de sortir le Motion Design par IA..."
    },
    {
        "id": "iWoTS-c6Fbg",
        "videoId": "iWoTS-c6Fbg",
        "title": "Créer ton Agent IA simplement ! (Sans coder)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=iWoTS-c6Fbg",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Créer ton Agent IA simplement ! (Sans coder)..."
    },
    {
        "id": "jLuWKwf6-O4",
        "videoId": "jLuWKwf6-O4",
        "title": "Scaler les LLM avec Loopie #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=jLuWKwf6-O4",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Scaler les LLM avec Loopie #actu..."
    },
    {
        "id": "XMwq41AH2X4",
        "videoId": "XMwq41AH2X4",
        "title": "DeepSeek vient d’humilier ChatGPT et Claude (actu IA)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=XMwq41AH2X4",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : DeepSeek vient d’humilier ChatGPT et Claude (actu IA)..."
    },
    {
        "id": "im6rjBitL9M",
        "videoId": "im6rjBitL9M",
        "title": "Les 7 Hacks pour ne plus JAMAIS Atteindre la Limite de Claude",
        "author": "Lucas Reverdy",
        "source": "@reverdybusiness",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=im6rjBitL9M",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Lucas Reverdy : Les 7 Hacks pour ne plus JAMAIS Atteindre la Limite de Claude..."
    },
    {
        "id": "aYHX0hwN8lA",
        "videoId": "aYHX0hwN8lA",
        "title": "DeepSeek vient de multiplier ses performances par 7",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=aYHX0hwN8lA",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : DeepSeek vient de multiplier ses performances par 7..."
    },
    {
        "id": "rQuiE7S7Jzg",
        "videoId": "rQuiE7S7Jzg",
        "title": "Claude Skills : Tu peux enfin TOUT automatiser en montrant ton ÉCRAN !",
        "author": "Aurélien Fagioli",
        "source": "@AurelienAutomatisation",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=rQuiE7S7Jzg",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Aurélien Fagioli : Claude Skills : Tu peux enfin TOUT automatiser en montrant ton ÉCRAN !..."
    },
    {
        "id": "eWN535AMIzQ",
        "videoId": "eWN535AMIzQ",
        "title": "Créer ton 1er Agent IA sans coder en 30 min ! (je te montre TOUT)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-04",
        "url": "https://www.youtube.com/watch?v=eWN535AMIzQ",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Créer ton 1er Agent IA sans coder en 30 min ! (je te montre TOUT)..."
    },
    {
        "id": "ALW2Yy0nUhI",
        "videoId": "ALW2Yy0nUhI",
        "title": "Interdiction des réseaux sociaux aux moins de 15 ans. L'enfumage.",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-08-04",
        "url": "https://www.youtube.com/watch?v=ALW2Yy0nUhI",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Interdiction des réseaux sociaux aux moins de 15 ans. L'enfumage...."
    },
    {
        "id": "mwT6tsD6KqE",
        "videoId": "mwT6tsD6KqE",
        "title": "Google automatise l’ordinateur quantique #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-04",
        "url": "https://www.youtube.com/watch?v=mwT6tsD6KqE",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Google automatise l’ordinateur quantique #actu..."
    },
    {
        "id": "fsw03ZXHJik",
        "videoId": "fsw03ZXHJik",
        "title": "Mistral sera bientôt partout (apprenez-le maintenant)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-04",
        "url": "https://www.youtube.com/watch?v=fsw03ZXHJik",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Mistral sera bientôt partout (apprenez-le maintenant)..."
    },
    {
        "id": "aMplSiLs8cs",
        "videoId": "aMplSiLs8cs",
        "title": "Pourquoi le Reward Hacking inquiète de plus en plus",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-03",
        "url": "https://www.youtube.com/watch?v=aMplSiLs8cs",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Pourquoi le Reward Hacking inquiète de plus en plus..."
    },
    {
        "id": "gBY3xIaDquY",
        "videoId": "gBY3xIaDquY",
        "title": "J'ai dépensé 50.000€ en moins d'1 an dans des formations (voici ce que j'ai appris)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-02",
        "url": "https://www.youtube.com/watch?v=gBY3xIaDquY",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : J'ai dépensé 50.000€ en moins d'1 an dans des formations (voici ce que j'ai appris)..."
    },
    {
        "id": "Vv1eXHqOZlI",
        "videoId": "Vv1eXHqOZlI",
        "title": "Comment Vivre de l'IA en 2026 (sans compétence technique)",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-08-02",
        "url": "https://www.youtube.com/watch?v=Vv1eXHqOZlI",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comment Vivre de l'IA en 2026 (sans compétence technique)..."
    },
    {
        "id": "UJIe9dWqlyY",
        "videoId": "UJIe9dWqlyY",
        "title": "Pourquoi Kimi K3 inquiète autant les États-Unis ?",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-02",
        "url": "https://www.youtube.com/watch?v=UJIe9dWqlyY",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Pourquoi Kimi K3 inquiète autant les États-Unis ?..."
    },
    {
        "id": "NvE2yPI77KA",
        "videoId": "NvE2yPI77KA",
        "title": "Comment vendre de l'ia en 2026 🔥(TUTO COMPLET)",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-07-30",
        "url": "https://www.youtube.com/watch?v=NvE2yPI77KA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Comment vendre de l'ia en 2026 🔥(TUTO COMPLET)..."
    },
    {
        "id": "_-oxY6Q8BBs",
        "videoId": "_-oxY6Q8BBs",
        "title": "L'outil IA n°1 sur Github vient de RÉSOUDRE le problème de recherche sur Claude",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-29",
        "url": "https://www.youtube.com/watch?v=_-oxY6Q8BBs",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : L'outil IA n°1 sur Github vient de RÉSOUDRE le problème de recherche sur Claude..."
    },
    {
        "id": "-QWqZvcmNoY",
        "videoId": "-QWqZvcmNoY",
        "title": "Crée tes propres skills claude en t'enregistrant! 🎬",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-28",
        "url": "https://www.youtube.com/watch?v=-QWqZvcmNoY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Crée tes propres skills claude en t'enregistrant! 🎬..."
    },
    {
        "id": "IN_knFr6tQ4",
        "videoId": "IN_knFr6tQ4",
        "title": "Comment maîtriser l'IA mieux que 95% des business (5 secrets)",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-07-27",
        "url": "https://www.youtube.com/watch?v=IN_knFr6tQ4",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comment maîtriser l'IA mieux que 95% des business (5 secrets)..."
    },
    {
        "id": "flQLseCGsHU",
        "videoId": "flQLseCGsHU",
        "title": "Ce skill Claude va rendre ton IA humaine 👀",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-27",
        "url": "https://www.youtube.com/watch?v=flQLseCGsHU",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Ce skill Claude va rendre ton IA humaine 👀..."
    },
    {
        "id": "pk-_1sanvCw",
        "videoId": "pk-_1sanvCw",
        "title": "Claude crée maintenant tes propres outils IA (grâce aux artifacts)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-07-27",
        "url": "https://www.youtube.com/watch?v=pk-_1sanvCw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Claude crée maintenant tes propres outils IA (grâce aux artifacts)..."
    },
    {
        "id": "de8Dp2EWo0g",
        "videoId": "de8Dp2EWo0g",
        "title": "J'ai analysé 85 Agences IA, voici ce qui marche en 2026",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-26",
        "url": "https://www.youtube.com/watch?v=de8Dp2EWo0g",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : J'ai analysé 85 Agences IA, voici ce qui marche en 2026..."
    },
    {
        "id": "dqGe3j8o-UM",
        "videoId": "dqGe3j8o-UM",
        "title": "Claude Code + Higgsfield créent vos pubs à votre place ! (marque, produits, UGC)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-26",
        "url": "https://www.youtube.com/watch?v=dqGe3j8o-UM",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Claude Code + Higgsfield créent vos pubs à votre place ! (marque, produits, UGC)..."
    },
    {
        "id": "FIpgh1PCM14",
        "videoId": "FIpgh1PCM14",
        "title": "Pourquoi Kimi K3 inquiète autant les États-Unis",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-07-25",
        "url": "https://www.youtube.com/watch?v=FIpgh1PCM14",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Pourquoi Kimi K3 inquiète autant les États-Unis..."
    },
    {
        "id": "r6jn9iJJCfo",
        "videoId": "r6jn9iJJCfo",
        "title": "Opus 5 vient de tuer Fable (Vraiment)",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-25",
        "url": "https://www.youtube.com/watch?v=r6jn9iJJCfo",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : Opus 5 vient de tuer Fable (Vraiment)..."
    },
    {
        "id": "ZLw7kIgNcQE",
        "videoId": "ZLw7kIgNcQE",
        "title": "100 jours avec Hermes Agent résumé en 16 minutes",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-24",
        "url": "https://www.youtube.com/watch?v=ZLw7kIgNcQE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : 100 jours avec Hermes Agent résumé en 16 minutes..."
    },
    {
        "id": "JIFgklJGj2w",
        "videoId": "JIFgklJGj2w",
        "title": "Arrêtez de créer des Agents IA, créez des Loops !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-23",
        "url": "https://www.youtube.com/watch?v=JIFgklJGj2w",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Arrêtez de créer des Agents IA, créez des Loops !..."
    },
    {
        "id": "l1zVp3wOBSg",
        "videoId": "l1zVp3wOBSg",
        "title": "Gemini 3.6 Flash : Ne vous fiez pas aux Benchmarks",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-23",
        "url": "https://www.youtube.com/watch?v=l1zVp3wOBSg",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : Gemini 3.6 Flash : Ne vous fiez pas aux Benchmarks..."
    },
    {
        "id": "LGiaRxIsnzk",
        "videoId": "LGiaRxIsnzk",
        "title": "Il a fait son site SEUL avec CLAUDE CODE en 2 jours",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=LGiaRxIsnzk",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : Il a fait son site SEUL avec CLAUDE CODE en 2 jours..."
    },
    {
        "id": "NQJPlvwVFOE",
        "videoId": "NQJPlvwVFOE",
        "title": "Comment Créer des Skills Claude comme un PRO (tuto complet)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=NQJPlvwVFOE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment Créer des Skills Claude comme un PRO (tuto complet)..."
    },
    {
        "id": "FD0i-wFhnC4",
        "videoId": "FD0i-wFhnC4",
        "title": "Arrêtez les prompts. Passez aux Loops (Le futur des agents IA)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=FD0i-wFhnC4",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Arrêtez les prompts. Passez aux Loops (Le futur des agents IA)..."
    },
    {
        "id": "RutkqDcQZL0",
        "videoId": "RutkqDcQZL0",
        "title": "Comment utiliser Hermes GRATUITEMENT �� VIE",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=RutkqDcQZL0",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : Comment utiliser Hermes GRATUITEMENT �� VIE..."
    },
    {
        "id": "F9YcVlyZahk",
        "videoId": "F9YcVlyZahk",
        "title": "Hermes V0.19 Vient De Révolutionner Les Agents IA - Voici pourquoi",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-21",
        "url": "https://www.youtube.com/watch?v=F9YcVlyZahk",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : Hermes V0.19 Vient De Révolutionner Les Agents IA - Voici pourquoi..."
    },
    {
        "id": "hJziz2RGFbc",
        "videoId": "hJziz2RGFbc",
        "title": "IA = média ? L’Allemagne tranche",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-20",
        "url": "https://www.youtube.com/watch?v=hJziz2RGFbc",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : IA = média ? L’Allemagne tranche..."
    },
    {
        "id": "IziMU2lXstI",
        "videoId": "IziMU2lXstI",
        "title": "NotebookLM : 5 extensions qui comblent ses plus gros manques",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-07-20",
        "url": "https://www.youtube.com/watch?v=IziMU2lXstI",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : NotebookLM : 5 extensions qui comblent ses plus gros manques..."
    },
    {
        "id": "3q1slkjnJNE",
        "videoId": "3q1slkjnJNE",
        "title": "Comment je mène un Audit IA chez un client à 5M€ (extraits réels)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-19",
        "url": "https://www.youtube.com/watch?v=3q1slkjnJNE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment je mène un Audit IA chez un client à 5M€ (extraits réels)..."
    },
    {
        "id": "ocFNQTfj49U",
        "videoId": "ocFNQTfj49U",
        "title": "Deepseek a résolu le plus gros problème de l’IA",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-07-19",
        "url": "https://www.youtube.com/watch?v=ocFNQTfj49U",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Deepseek a résolu le plus gros problème de l’IA..."
    },
    {
        "id": "cBH0KT9SG_c",
        "videoId": "cBH0KT9SG_c",
        "title": "La nouvelle fonctionnalité de n8n est INCROYABLE (mieux que Claude Code?)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-19",
        "url": "https://www.youtube.com/watch?v=cBH0KT9SG_c",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : La nouvelle fonctionnalité de n8n est INCROYABLE (mieux que Claude Code?)..."
    },
    {
        "id": "p9hfvCiffB4",
        "videoId": "p9hfvCiffB4",
        "title": "GPT-Red attaque les IA d’OpenAI",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-18",
        "url": "https://www.youtube.com/watch?v=p9hfvCiffB4",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : GPT-Red attaque les IA d’OpenAI..."
    },
    {
        "id": "cxo-wcAiEcU",
        "videoId": "cxo-wcAiEcU",
        "title": "OpenAI lance son premier gadget",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-18",
        "url": "https://www.youtube.com/watch?v=cxo-wcAiEcU",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : OpenAI lance son premier gadget..."
    },
    {
        "id": "Uw9qdnKekR0",
        "videoId": "Uw9qdnKekR0",
        "title": "Kimi K3 : l’IA ouverte qui choque",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-17",
        "url": "https://www.youtube.com/watch?v=Uw9qdnKekR0",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Kimi K3 : l’IA ouverte qui choque..."
    },
    {
        "id": "gxeROwXU_AA",
        "videoId": "gxeROwXU_AA",
        "title": "Une IA, un objet IA, et la pire idée de l'IA : joyeux été !",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-17",
        "url": "https://www.youtube.com/watch?v=gxeROwXU_AA",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Une IA, un objet IA, et la pire idée de l'IA : joyeux été !..."
    },
    {
        "id": "ZEbdDeSrJOU",
        "videoId": "ZEbdDeSrJOU",
        "title": "Une IA, un objet IA, et la pire idée de l'IA : joyeux été !",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-17",
        "url": "https://www.youtube.com/watch?v=ZEbdDeSrJOU",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Une IA, un objet IA, et la pire idée de l'IA : joyeux été !..."
    },
    {
        "id": "1xAS2WE3uUE",
        "videoId": "1xAS2WE3uUE",
        "title": "AGI : Google veut un gendarme global",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-17",
        "url": "https://www.youtube.com/watch?v=1xAS2WE3uUE",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : AGI : Google veut un gendarme global..."
    },
    {
        "id": "JnUPQ0lwgpI",
        "videoId": "JnUPQ0lwgpI",
        "title": "Voici Copilot Cowork, l'IA qui automatise vos tâches !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-16",
        "url": "https://www.youtube.com/watch?v=JnUPQ0lwgpI",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Voici Copilot Cowork, l'IA qui automatise vos tâches !..."
    },
    {
        "id": "7_7WOjZswh4",
        "videoId": "7_7WOjZswh4",
        "title": "FSB : 16 ans d'espionnage en France",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-16",
        "url": "https://www.youtube.com/watch?v=7_7WOjZswh4",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : FSB : 16 ans d'espionnage en France..."
    },
    {
        "id": "MlFANuVPvsk",
        "videoId": "MlFANuVPvsk",
        "title": "Claude gratuit pour profs US",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-16",
        "url": "https://www.youtube.com/watch?v=MlFANuVPvsk",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Claude gratuit pour profs US..."
    },
    {
        "id": "h3pjyTfOLys",
        "videoId": "h3pjyTfOLys",
        "title": "Chat Control : chiffrement sauvé ?",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-15",
        "url": "https://www.youtube.com/watch?v=h3pjyTfOLys",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Chat Control : chiffrement sauvé ?..."
    },
    {
        "id": "yxr6VO1jKnk",
        "videoId": "yxr6VO1jKnk",
        "title": "L'Europe à la ramasse sur l'IA, le cyber, les réseaux... Alerte !",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-15",
        "url": "https://www.youtube.com/watch?v=yxr6VO1jKnk",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : L'Europe à la ramasse sur l'IA, le cyber, les réseaux... Alerte !..."
    },
    {
        "id": "EBe3w4Bpd2k",
        "videoId": "EBe3w4Bpd2k",
        "title": "L'Europe à la ramasse sur l'IA, le cyber, les réseaux... Alerte !",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-15",
        "url": "https://www.youtube.com/watch?v=EBe3w4Bpd2k",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : L'Europe à la ramasse sur l'IA, le cyber, les réseaux... Alerte !..."
    },
    {
        "id": "LbQT8bgxT1E",
        "videoId": "LbQT8bgxT1E",
        "title": "Meta casse les prix de l’API IA",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-15",
        "url": "https://www.youtube.com/watch?v=LbQT8bgxT1E",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Meta casse les prix de l’API IA..."
    },
    {
        "id": "9KZ0I8bVh3A",
        "videoId": "9KZ0I8bVh3A",
        "title": "Apple vs OpenAI : secrets volés ?",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-07-14",
        "url": "https://www.youtube.com/watch?v=9KZ0I8bVh3A",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Apple vs OpenAI : secrets volés ?..."
    },
    {
        "id": "C9oGaD_L29M",
        "videoId": "C9oGaD_L29M",
        "title": "J'ai testé l’énorme mise à jour de ChatGPT ! (ChatGPT Work + GPT-5.6)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-13",
        "url": "https://www.youtube.com/watch?v=C9oGaD_L29M",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : J'ai testé l’énorme mise à jour de ChatGPT ! (ChatGPT Work + GPT-5.6)..."
    },
    {
        "id": "Sj3Z1-LO-I8",
        "videoId": "Sj3Z1-LO-I8",
        "title": "Mon système : publier régulier avec 1 jour par semaine",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-07-13",
        "url": "https://www.youtube.com/watch?v=Sj3Z1-LO-I8",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Mon système : publier régulier avec 1 jour par semaine..."
    },
    {
        "id": "rx7F_9Vm35Y",
        "videoId": "rx7F_9Vm35Y",
        "title": "ChatGPT travaille enfin à votre place ! (ChatGPT Work &amp; GPT-5.6)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-12",
        "url": "https://www.youtube.com/watch?v=rx7F_9Vm35Y",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : ChatGPT travaille enfin à votre place ! (ChatGPT Work &amp; GPT-5.6)..."
    },
    {
        "id": "oU2slLP15VA",
        "videoId": "oU2slLP15VA",
        "title": "La nouvelle méthode pour utiliser Claude IA sans prompt",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-07-12",
        "url": "https://www.youtube.com/watch?v=oU2slLP15VA",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : La nouvelle méthode pour utiliser Claude IA sans prompt..."
    },
    {
        "id": "5dF9rDlMGhE",
        "videoId": "5dF9rDlMGhE",
        "title": "Le nouveau ChatGPT est DISPO : voici tout ce qu’il peut faire.",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-07-09",
        "url": "https://www.youtube.com/watch?v=5dF9rDlMGhE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Le nouveau ChatGPT est DISPO : voici tout ce qu’il peut faire...."
    },
    {
        "id": "ReWSbxmIITM",
        "videoId": "ReWSbxmIITM",
        "title": "Comprendre le Fonctionnement des LLM : Guide Complet Débutant",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-07-05",
        "url": "https://www.youtube.com/watch?v=ReWSbxmIITM",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comprendre le Fonctionnement des LLM : Guide Complet Débutant..."
    },
    {
        "id": "MEgLPh5FAqY",
        "videoId": "MEgLPh5FAqY",
        "title": "Les boucles d'agents IA : ce que personne te dit (et quand NE PAS en faire)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-05",
        "url": "https://www.youtube.com/watch?v=MEgLPh5FAqY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Les boucles d'agents IA : ce que personne te dit (et quand NE PAS en faire)..."
    },
    {
        "id": "IbSrpvhkCTQ",
        "videoId": "IbSrpvhkCTQ",
        "title": "Anthropic x Samsung: La fin de l'hégémonie Nvidia? - Puces IA personnalisées: La nouvelle stratégie",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-07-03",
        "url": "https://www.youtube.com/watch?v=IbSrpvhkCTQ",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Anthropic x Samsung: La fin de l'hégémonie Nvidia? - Puces IA personnalisées: La nouvelle stratégie..."
    },
    {
        "id": "B3XeYkaZrjY",
        "videoId": "B3XeYkaZrjY",
        "title": "J'ai créé des pubs pro en 5 minutes - Claude Fable 5 + Higgsfield MCP !",
        "author": "Aurélien Fagioli",
        "source": "@AurelienAutomatisation",
        "date": "2026-07-03",
        "url": "https://www.youtube.com/watch?v=B3XeYkaZrjY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Aurélien Fagioli : J'ai créé des pubs pro en 5 minutes - Claude Fable 5 + Higgsfield MCP !..."
    },
    {
        "id": "eNzSQbz0slo",
        "videoId": "eNzSQbz0slo",
        "title": "La seule chose que l'IA ne peut pas copier",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-07-01",
        "url": "https://www.youtube.com/watch?v=eNzSQbz0slo",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : La seule chose que l'IA ne peut pas copier..."
    },
    {
        "id": "ffwftm89rQg",
        "videoId": "ffwftm89rQg",
        "title": "Claude Sonnet 5 : l'IA qui fait tout... sans cramer vos tokens.",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-07-01",
        "url": "https://www.youtube.com/watch?v=ffwftm89rQg",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Claude Sonnet 5 : l'IA qui fait tout... sans cramer vos tokens...."
    },
    {
        "id": "TbpFNzcknPA",
        "videoId": "TbpFNzcknPA",
        "title": "L'IA peut-elle remplacer un CEO? Les résultats de l'étude - Seules 3 IA ont réussi ce test de CEO",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-06-30",
        "url": "https://www.youtube.com/watch?v=TbpFNzcknPA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : L'IA peut-elle remplacer un CEO? Les résultats de l'étude - Seules 3 IA ont réussi ce test de CEO..."
    },
    {
        "id": "ukf9DBoyas8",
        "videoId": "ukf9DBoyas8",
        "title": "L'étape que tout le monde saute avant de choisir son IA",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-06-29",
        "url": "https://www.youtube.com/watch?v=ukf9DBoyas8",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : L'étape que tout le monde saute avant de choisir son IA..."
    },
    {
        "id": "ZCdYOnKdPp8",
        "videoId": "ZCdYOnKdPp8",
        "title": "Vendre une infrastructure IA 3000€ sans être un vendeur (Matrice POVI)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-06-28",
        "url": "https://www.youtube.com/watch?v=ZCdYOnKdPp8",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Vendre une infrastructure IA 3000€ sans être un vendeur (Matrice POVI)..."
    },
    {
        "id": "JKD_mD70ml8",
        "videoId": "JKD_mD70ml8",
        "title": "J’ai confié mes tâches à Copilot Cowork : le résultat est bluffant !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-06-28",
        "url": "https://www.youtube.com/watch?v=JKD_mD70ml8",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : J’ai confié mes tâches à Copilot Cowork : le résultat est bluffant !..."
    },
    {
        "id": "gl7sgL9pVSE",
        "videoId": "gl7sgL9pVSE",
        "title": "Claude IA fait maintenant TOUT à votre place",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-06-28",
        "url": "https://www.youtube.com/watch?v=gl7sgL9pVSE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Claude IA fait maintenant TOUT à votre place..."
    },
    {
        "id": "DgqKAlZuM_A",
        "videoId": "DgqKAlZuM_A",
        "title": "Fable 5 de RETOUR : Pourquoi l'IA était interdite aux USA?- Mythos, GPT 5.6: La fin des restrictions",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-06-28",
        "url": "https://www.youtube.com/watch?v=DgqKAlZuM_A",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Fable 5 de RETOUR : Pourquoi l'IA était interdite aux USA?- Mythos, GPT 5.6: La fin des restrictions..."
    },
    {
        "id": "s3DthPRppsc",
        "videoId": "s3DthPRppsc",
        "title": "L'agentique IA, le nouveau dropshipping",
        "author": "Baptiste Simard - IA",
        "source": "@BaptIA",
        "date": "2026-06-27",
        "url": "https://www.youtube.com/watch?v=s3DthPRppsc",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Baptiste Simard - IA : L'agentique IA, le nouveau dropshipping..."
    },
    {
        "id": "WyA985f8kqg",
        "videoId": "WyA985f8kqg",
        "title": "Les 2 seuls VRAIS BUSINESS IA à lancer en 2026",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-06-26",
        "url": "https://www.youtube.com/watch?v=WyA985f8kqg",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Les 2 seuls VRAIS BUSINESS IA à lancer en 2026..."
    },
    {
        "id": "pIa4jZuSlwI",
        "videoId": "pIa4jZuSlwI",
        "title": "L'unique secret pour survivre à l'IA en 2026",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-06-24",
        "url": "https://www.youtube.com/watch?v=pIa4jZuSlwI",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : L'unique secret pour survivre à l'IA en 2026..."
    },
    {
        "id": "i6fNZBNYJ70",
        "videoId": "i6fNZBNYJ70",
        "title": "Cette nouvelle IA va automatiser ton travail! - OpenAI Record &amp; Replay: Automatisez TOUT en 3 étapes",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-06-24",
        "url": "https://www.youtube.com/watch?v=i6fNZBNYJ70",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Jonas Ekanbo : Cette nouvelle IA va automatiser ton travail! - OpenAI Record &amp; Replay: Automatisez TOUT en 3 ét..."
    },
    {
        "id": "nHXND_R4Jy8",
        "videoId": "nHXND_R4Jy8",
        "title": "Claude IA : le tutoriel facile pour débutant",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-06-24",
        "url": "https://www.youtube.com/watch?v=nHXND_R4Jy8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Claude IA : le tutoriel facile pour débutant..."
    },
    {
        "id": "_9o9t7kJWUA",
        "videoId": "_9o9t7kJWUA",
        "title": "YouTube Short",
        "author": "Baptiste Simard - IA",
        "source": "@BaptIA",
        "date": "2026-06-24",
        "url": "https://www.youtube.com/watch?v=_9o9t7kJWUA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Baptiste Simard - IA : YouTube Short..."
    }
];
